import { useEffect, useMemo, useState } from "react";
import { getSettings } from "../services/settingsService";
import { subscribeToWorkspaceData } from "../services/workspaceEvents";

export type AppLocale = "uz" | "ru";

const RU: Record<string, string> = {
  "nav.main": "ГЛАВНОЕ", "nav.system": "СИСТЕМА", "nav.home": "Главная", "nav.ai": "AI помощник", "nav.calendar": "Календарь", "nav.tasks": "Задачи", "nav.reminders": "Напоминания", "nav.files": "Файлы", "nav.settings": "Настройки", "nav.profile": "Профиль", "nav.logout": "Выйти", "nav.ready": "Готов к работе", "nav.workspace": "AI рабочее пространство",
  "top.search": "Поиск...", "top.search.none": "Ничего не найдено.", "top.notifications": "Уведомления", "top.allRead": "Все прочитано", "top.new": "новых", "top.none": "Уведомлений пока нет.", "top.notificationSettings": "Настройки уведомлений", "top.now": "сейчас", "top.minutes": "мин", "top.hours": "ч", "top.days": "дн",
  "common.create": "Создать", "common.save": "Сохранить", "common.cancel": "Отмена", "common.delete": "Удалить", "common.edit": "Изменить", "common.search": "Поиск", "common.all": "Все", "common.today": "Сегодня", "common.completed": "Выполнено", "common.active": "Активные", "common.overdue": "Просрочено", "common.retry": "Повторить", "common.loading": "Загрузка...",
  "tasks.title": "Задачи", "tasks.new": "Новая задача", "tasks.search": "Поиск задач...", "tasks.important": "Важные", "tasks.inProgress": "В процессе", "tasks.duplicate": "Дублировать", "tasks.subtitle": "Управляйте делами на сегодня и держите прогресс под контролем.", "tasks.progress": "Прогресс", "tasks.todayProgress": "ПРОГРЕСС НА СЕГОДНЯ", "tasks.todayWork": "Задачи на сегодня", "tasks.all": "Все", "tasks.today": "Сегодня", "tasks.overdue": "Просроченные", "tasks.done": "Выполненные", "tasks.sort": "Сортировка", "tasks.sortDeadline": "По сроку", "tasks.sortPriority": "По важности", "tasks.sortTitle": "По названию", "tasks.noTasks": "Задач пока нет", "tasks.notFound": "Задачи не найдены", "tasks.tryFilter": "Попробуйте другой фильтр или поисковый запрос.", "tasks.priority": "ПРИОРИТЕТ", "tasks.priorityHelp": "Дела, которым стоит уделить внимание сегодня.", "tasks.add": "Добавить задачу", "tasks.edit": "Редактировать задачу", "tasks.name": "Название задачи", "tasks.description": "Краткое описание...", "tasks.create": "Создать задачу", "tasks.markDone": "Отметить выполненной", "tasks.makeActive": "Вернуть в активные", "tasks.editAction": "Редактировать", "tasks.copy": "Создать копию", "tasks.delete": "Удалить", "tasks.status": "Статус задачи", "tasks.statusNew": "Новая", "tasks.statusProgress": "В процессе", "tasks.moveProgress": "Перевести в работу", "tasks.movedProgress": "Задача переведена в работу", "tasks.statusError": "Не удалось обновить статус задачи",
  "reminders.title": "Напоминания", "reminders.new": "Новое напоминание", "reminders.search": "Поиск напоминаний...", "reminders.snooze": "Отложить на 10 минут", "reminders.scheduled": "Запланировано", "reminders.subtitle": "Не пропускайте важные дела и возвращайтесь к ним вовремя.", "reminders.all": "Все", "reminders.active": "Активные", "reminders.overdue": "Просроченные", "reminders.done": "Выполненные", "reminders.noItems": "Напоминаний пока нет", "reminders.notFound": "Напоминания не найдены", "reminders.edit": "Редактировать напоминание", "reminders.name": "Название напоминания", "reminders.description": "Краткое описание...", "reminders.create": "Создать напоминание",
  "calendar.title": "Календарь", "calendar.new": "Новая встреча", "calendar.month": "Месяц", "calendar.week": "Неделя", "calendar.day": "День", "calendar.location": "Место / ссылка", "calendar.conflict": "На это время уже запланирована встреча.", "calendar.subtitle": "Управляйте встречами и ежедневным расписанием.", "calendar.today": "Сегодня", "calendar.emptyDay": "На выбранный день встреч пока нет.", "calendar.todayPlan": "ПЛАН НА СЕГОДНЯ", "calendar.edit": "Редактировать встречу", "calendar.name": "Название встречи", "calendar.participant": "Участник", "calendar.description": "Описание", "calendar.save": "Сохранить", "calendar.createEvent": "Создать событие", "calendar.noReminder": "Без напоминания",
  "files.title": "Файлы", "files.upload": "Загрузить", "files.folder": "Создать папку", "files.search": "Поиск файлов...", "files.recent": "Последние файлы", "files.download": "Скачать", "files.open": "Открыть", "files.safe": "Безопасное хранение", "files.subtitle": "Храните и управляйте рабочими документами в одном месте.", "files.folders": "Папки", "files.all": "Все файлы", "files.rename": "Переименовать", "files.delete": "Удалить", "files.back": "Назад", "files.empty": "Файлов пока нет", "files.emptyHelp": "Перетащите файл сюда или нажмите «Загрузить».", "files.newFolder": "Новая папка", "files.folderName": "Название папки", "files.save": "Сохранить", "files.cancel": "Отмена", "files.create": "Создать",
  "settings.title": "Настройки", "settings.subtitle": "Аккаунт, внешний вид, уведомления и интеграции.", "settings.account": "Аккаунт", "settings.security": "Безопасность", "settings.appearance": "Внешний вид", "settings.notifications": "Уведомления", "settings.ai": "AI помощник", "settings.language": "Язык", "settings.integrations": "Интеграции",
  "integrations.connected": "Подключено", "integrations.connect": "Подключить", "integrations.manage": "Управлять", "integrations.soon": "Скоро", "integrations.unavailable": "Пока недоступно",
  "ai.workspace": "AI рабочее пространство", "ai.quick": "Быстрые действия", "ai.history": "Недавние чаты", "ai.newChat": "Новый чат", "ai.historyLoading": "История загружается…", "ai.noHistory": "Сохранённых чатов пока нет.", "ai.messages": "сообщ.", "ai.greeting": "ПРИВЕТ, Я QULAY AI", "ai.question": "Чем я могу помочь сегодня?", "ai.subtitle": "Планируйте день, создавайте задачи или просто начните разговор.", "ai.todayPlan": "Покажи план на сегодня", "ai.newTask": "Создай новую задачу", "ai.newReminder": "Добавь напоминание", "ai.voice": "Открыть голосовой режим", "ai.online": "Онлайн · Готов", "ai.historySearch": "Поиск по истории чатов...", "ai.renameChat": "Переименовать чат", "ai.historyNotFound": "Подходящий чат не найден.",
  "dashboard.title": "Главная", "dashboard.today": "Сегодня", "dashboard.integrations": "Интеграции",
  "quick.title": "Быстрые действия", "quick.subtitle": "Часто используемые реальные функции", "quick.all": "Управлять через AI", "quick.telegram": "Написать в Telegram", "quick.telegramHelp": "Найдите контакт через AI и отправьте после подтверждения", "quick.calendar": "Создать встречу", "quick.calendarHelp": "Новая встреча в календаре", "quick.task": "Создать задачу", "quick.taskHelp": "Задача со сроком и приоритетом", "quick.reminder": "Добавить напоминание", "quick.reminderHelp": "Получите уведомление в нужное время", "quick.files": "Открыть файлы", "quick.filesHelp": "Документы, PDF и файлы Drive", "quick.ai": "AI помощник", "quick.aiHelp": "План, вопрос или другое действие",
};

export const getLocale = (): AppLocale => getSettings().language === "Русский" ? "ru" : "uz";
export const translate = (key: string, fallback: string, locale: AppLocale): string => locale === "ru" ? RU[key] ?? fallback : fallback;

export const useI18n = () => {
  const [locale, setLocale] = useState<AppLocale>(getLocale);
  useEffect(() => subscribeToWorkspaceData("settings", () => {
    const next = getLocale();
    setLocale(next);
    document.documentElement.lang = next;
  }), []);
  useEffect(() => { document.documentElement.lang = locale; }, [locale]);
  return useMemo(() => ({ locale, t: (key: string, fallback: string) => translate(key, fallback, locale) }), [locale]);
};
