import React,{useMemo,useState} from 'react'
import {ShoppingBag,Boxes,Users,PackageCheck,Sparkles,Plus,ShoppingCart,BarChart3,WalletCards,AlertTriangle,ArrowUpRight} from 'lucide-react'
import {Card,KPI,PageHeader,Money,Status} from '../components/UI'
import {useApp} from '../state/AppContext'
import {useNavigate} from 'react-router-dom'

export default function Dashboard(){
  const {state,currentEmployee,can}=useApp(),nav=useNavigate();const [trendPeriod,setTrendPeriod]=useState('7 kun')
  const stats=useMemo(()=>{const sales=state.sales.reduce((a,x)=>a+x.amount,0),stockValue=state.products.reduce((a,p)=>a+p.cost*p.stock,0),stock=state.products.reduce((a,p)=>a+p.stock,0),low=state.products.filter(p=>p.stock<=p.minStock&&p.stock>0).length,out=state.products.filter(p=>p.stock===0).length;return {sales,stockValue,stock,low,out}},[state])
  const trend=useMemo(()=>trendPeriod==='7 kun'?{values:[38,56,74,48,65,78,86],labels:['30 Aug','31 Aug','1 Sep','2 Sep','3 Sep','4 Sep','5 Sep']}:trendPeriod==='30 kun'?{values:[31,39,44,52,48,58,61,55,63,69,66,72],labels:['7 Avg','10 Avg','13 Avg','16 Avg','19 Avg','22 Avg','25 Avg','28 Avg','31 Avg','2 Sep','4 Sep','5 Sep']}:{values:[34,42,48,45,56,61,58,69,74],labels:['Yan','Fev','Mar','Apr','May','Iyun','Iyul','Avg','Sen']},[trendPeriod])
  const cycleTrend=()=>setTrendPeriod(v=>v==='7 kun'?'30 kun':v==='30 kun'?'Yil':'7 kun')
  return <>
    <PageHeader title={`Xush kelibsiz, ${currentEmployee?.name||'User'}!`} subtitle="Bugungi biznes faoliyatingiz haqida qisqa va aniq ko‘rinish." actions={can('ai')?<button className="soft-glass-btn" onClick={()=>nav('/ai?context=dashboard')}><Sparkles/> AI bilan tahlil</button>:null}/>
    <div className="kpi-grid dashboard-kpis"><KPI label="Bugungi savdo" value={<Money value={stats.sales}/>} delta="+18.5%" icon={<ShoppingBag/>} onClick={()=>nav('/sales')}/><KPI label="Savdolar" value={`${state.sales.length} ta`} delta="+8.1%" icon={<PackageCheck/>} onClick={()=>can('sales')&&nav('/sales?view=history')}/><KPI label="Ombor qiymati" value={<Money value={stats.stockValue}/>} delta="+4.2%" icon={<Boxes/>} onClick={()=>nav('/warehouse')}/><KPI label="Mijozlar" value={`${state.customers.length} ta`} delta="+15.4%" icon={<Users/>} onClick={()=>nav('/customers')}/></div>
    <div className="dashboard-main-grid">
      <Card className="chart-card"><div className="card-title"><b>Savdo dinamikasi</b><button className="tiny-pill" onClick={cycleTrend}>Oxirgi {trendPeriod}</button></div><div className="bars">{trend.values.map((x,i)=><div key={`${trendPeriod}-${i}`}><i style={{height:x+'%'}}/><span>{trend.labels[i]}</span></div>)}</div></Card>
      <div className="dashboard-right-stack">
        <Card><div className="card-title"><b>Eng ko‘p sotilgan mahsulotlar</b><button className="link-btn" onClick={()=>nav('/reports?view=products')}>Barchasi →</button></div><div className="rank-list compact">{state.products.slice(0,5).map((p,i)=><div key={p.id}><strong>{i+1}</strong><span>{p.name}</span><b>{Math.min(p.stock,245)} {p.unit}</b><Money value={p.price*Math.min(p.stock,245)}/></div>)}</div></Card>
        <Card><div className="card-title"><b>Ombor holati</b><button className="link-btn" onClick={()=>nav('/warehouse')}>Barchasi →</button></div><div className="stock-summary compact"><div className="donut"><b>{stats.stock}</b><small>jami qoldiq</small></div><div><p><i className="dot d0"/>Mavjud<b>{stats.stock}</b></p><p><i className="dot d1"/>Kam qoldi<b>{stats.low}</b></p><p><i className="dot d2"/>Tugagan<b>{stats.out}</b></p></div></div></Card>
      </div>
    </div>
    <div className="dashboard-bottom-grid"><Card><div className="card-title"><b>So‘nggi savdolar</b><button className="link-btn" onClick={()=>nav('/sales?view=history')}>Barchasi →</button></div><table><thead><tr><th>#</th><th>Mijoz</th><th>To‘lov</th><th>Summa</th><th>Vaqt</th><th>Status</th></tr></thead><tbody>{state.sales.slice(0,5).map(s=><tr key={s.id}><td><b>{s.id}</b></td><td>{s.customer}</td><td>{s.payment}</td><td><Money value={s.amount}/></td><td>{s.time}</td><td><Status>{s.status}</Status></td></tr>)}</tbody></table></Card><Card className="quick-actions-premium"><div className="card-title"><b>Tezkor amallar</b><span>Bir bosishda</span></div><div className="quick-grid premium">{can('sales','create')&&<button onClick={()=>nav('/pos')}><span className="quick-icon"><ShoppingBag/></span><b>Yangi savdo</b><small>POS ochish</small></button>}{can('products','create')&&<button onClick={()=>nav('/products')}><span className="quick-icon"><Plus/></span><b>Mahsulot qo‘shish</b><small>Katalog</small></button>}{can('purchases','create')&&<button onClick={()=>nav('/purchases')}><span className="quick-icon"><ShoppingCart/></span><b>Xarid yaratish</b><small>Supplier</small></button>}{can('reports')&&<button onClick={()=>nav('/reports')}><span className="quick-icon"><BarChart3/></span><b>Hisobot</b><small>Analitika</small></button>}</div><div className="dashboard-alert"><AlertTriangle/><span><b>{stats.low} ta mahsulot kam qolgan.</b><small>Omborda tekshirish kerak.</small></span><ArrowUpRight/></div></Card></div>
  </>
}
