import React,{useMemo,useRef,useState} from 'react'
import {useSearchParams} from 'react-router-dom'
import {UserPlus,Users,Clock,Percent,ShieldCheck,Search,Plus,DoorOpen,DoorClosed,CalendarCheck,WalletCards,History,Check,LockKeyhole,Settings2,Copy,FileText,Upload,AlertTriangle,Edit3,Ban,Archive,ReceiptText,ShoppingBag,Eye} from 'lucide-react'
import {PageHeader,Card,KPI,Money,Modal,Drawer,Field,Input,Select,Status,Toast,Toggle,Empty,Confirm} from '../components/UI'
import {useApp} from '../state/AppContext'

const moduleDefs=[
  ['sales','Savdo'],['pos','POS'],['products','Mahsulotlar'],['warehouse','Ombor'],['purchases','Xaridlar'],['customers','Mijozlar'],['suppliers','Supplierlar'],['finance','Moliya'],['reports','Hisobotlar'],['employees','Xodimlar'],['settings','Sozlamalar']
]
const actions=[['view','Ko‘rish'],['create','Yaratish'],['edit','Tahrirlash'],['approve','Tasdiqlash'],['reverse','Reverse'],['export','Export'],['print','Print']]
const sensitive=[['cost','Tannarx'],['grossProfit','Gross profit'],['netProfit','Net profit'],['payroll','Payroll'],['bank','Bank rekvizitlari'],['audit','Audit log']]
const n=v=>Number(v)||0
const minutes=t=>{if(!t)return 0;const [h,m]=t.split(':').map(Number);return h*60+(m||0)}

function normalizePermission(role,key){
  if(role?.permissions?.all)return Object.fromEntries(actions.map(([a])=>[a,true]))
  const raw=role?.permissions?.[key]
  if(raw&&typeof raw==='object')return Object.fromEntries(actions.map(([a])=>[a,!!raw[a]]))
  if(raw===true)return Object.fromEntries(actions.map(([a])=>[a,true]))
  if(raw==='read')return {view:true,create:false,edit:false,approve:false,reverse:false,export:true,print:true}
  if(raw==='limited')return {view:true,create:true,edit:false,approve:false,reverse:false,export:false,print:true}
  if(raw==='receiving')return {view:true,create:true,edit:true,approve:false,reverse:false,export:false,print:true}
  return Object.fromEntries(actions.map(([a])=>[a,false]))
}

export default function Employees(){
  const {state,addEmployee,updateEmployee,addRole,updateRole,openShift,closeShift,addPayrollAdjustment,saveAttendance,setPayrollStatus}=useApp()
  const [p]=useSearchParams(),view=p.get('view')||'all'
  const [create,setCreate]=useState(false),[edit,setEdit]=useState(null),[detail,setDetail]=useState(null),[role,setRole]=useState(false),[shift,setShift]=useState(false),[close,setClose]=useState(null),[adjust,setAdjust]=useState(null),[attendance,setAttendance]=useState(null),[payStatus,setPayStatus]=useState(null),[confirmBlock,setConfirmBlock]=useState(null),[toast,setToast]=useState('')
  return <>
    <PageHeader title="Xodimlar" subtitle="Xodimlar, ruxsatlar, smena, davomat, KPI va ish haqi." actions={<button className="primary-glass-btn" onClick={()=>setCreate(true)}><UserPlus/> Xodim qo‘shish</button>}/>
    {view==='all'&&<EmployeesList state={state} onOpen={setDetail}/>} 
    {view==='roles'&&<Roles state={state} onNew={()=>setRole(true)} addRole={addRole} updateRole={updateRole} toast={setToast}/>} 
    {view==='shifts'&&<Shifts state={state} onOpen={()=>setShift(true)} onClose={setClose}/>} 
    {view==='attendance'&&<Attendance state={state} onAdd={()=>setAttendance({})} onEdit={setAttendance}/>} 
    {view==='payroll'&&<Payroll state={state} onAdjust={setAdjust} onStatus={setPayStatus}/>} 
    {view==='activity'&&<Activity state={state}/>} 

    {create&&<EmployeeModal state={state} onClose={()=>setCreate(false)} onSave={v=>{addEmployee(v);setCreate(false);setToast('Xodim yaratildi. Vaqtinchalik login ma’lumotlari saqlandi.')}}/>}
    {edit&&<EmployeeModal state={state} employee={edit} onClose={()=>setEdit(null)} onSave={v=>{updateEmployee(edit.id,v);setEdit(null);setDetail(v=>v?{...v,...v}:v);setToast('Xodim ma’lumotlari yangilandi.')}}/>}
    {detail&&<EmployeeDetail state={state} employee={state.employees.find(e=>e.id===detail.id)||detail} onClose={()=>setDetail(null)} onEdit={e=>setEdit(e)} onUpdate={(id,patch)=>{updateEmployee(id,patch);setToast('Xodim holati yangilandi.')}} onBlock={e=>setConfirmBlock(e)}/>} 
    {role&&<RoleModal state={state} onClose={()=>setRole(false)} onSave={v=>{addRole(v);setRole(false);setToast('Yangi rol yaratildi.')}}/>}
    {shift&&<ShiftOpenModal state={state} onClose={()=>setShift(false)} onSave={v=>{openShift(v);setShift(false);setToast('Smena ochildi.')}}/>}
    {close&&<ShiftCloseModal shift={close} onClose={()=>setClose(null)} onSave={v=>{closeShift({...v,shiftId:close.id});setClose(null);setToast('Smena yopildi.')}}/>}
    {adjust&&<PayrollAdjust employee={adjust} onClose={()=>setAdjust(null)} onSave={v=>{addPayrollAdjustment(v);setAdjust(null);setToast('Payroll adjustment saqlandi.')}}/>}
    {attendance&&<AttendanceModal state={state} row={attendance.id?attendance:null} onClose={()=>setAttendance(null)} onSave={v=>{saveAttendance(v);setAttendance(null);setToast(attendance.id?'Davomat tuzatildi.':'Davomat kiritildi.')}}/>}
    {payStatus&&<PayrollStatusModal state={state} payroll={payStatus} onClose={()=>setPayStatus(null)} onSave={v=>{setPayrollStatus(v);setPayStatus(null);setToast(v.status==='To‘landi'?'Ish haqi to‘landi va Moliyaga yozildi.':'Payroll status yangilandi.')}}/>}
    <Confirm open={!!confirmBlock} onClose={()=>setConfirmBlock(null)} onConfirm={()=>{updateEmployee(confirmBlock.id,{status:confirmBlock.status==='Bloklangan'?'Faol':'Bloklangan'});setConfirmBlock(null);setToast('Xodim statusi yangilandi.')}} danger={confirmBlock?.status!=='Bloklangan'} title={confirmBlock?.status==='Bloklangan'?'Xodimni faollashtirish':'Xodimni bloklash'} text={confirmBlock?.status==='Bloklangan'?'Login va ish huquqlari qayta faollashadi.':'Xodim login qilolmaydi va yangi operatsiya bajara olmaydi.'} confirmText={confirmBlock?.status==='Bloklangan'?'Faollashtirish':'Bloklash'}/>
    <Toast message={toast} onDone={()=>setToast('')}/>
  </>
}

function EmployeesList({state,onOpen}){
  const [q,setQ]=useState(''),[role,setRole]=useState('Barchasi'),[status,setStatus]=useState('Barchasi'),[branch,setBranch]=useState('Barchasi')
  const rows=state.employees.filter(e=>(e.name+' '+e.phone+' '+e.login+' '+e.role).toLowerCase().includes(q.toLowerCase())&&(role==='Barchasi'||e.role===role)&&(status==='Barchasi'||e.status===status)&&(branch==='Barchasi'||e.branchId===branch))
  const lateToday=state.attendance.filter(a=>a.status==='Kechikdi').length
  return <>
    <div className="kpi-grid"><KPI label="Jami xodimlar" value={state.employees.length} icon={<Users/>}/><KPI label="Bugun ishda" value={state.attendance.filter(a=>['Ishda','Kechikdi'].includes(a.status)).length} icon={<Clock/>}/><KPI label="Kechikkanlar" value={lateToday} icon={<CalendarCheck/>} tone={lateToday?'orange':'blue'}/><KPI label="Faol rollar" value={state.roles.filter(r=>r.status!=='Arxiv').length} icon={<ShieldCheck/>}/></div>
    <Card><div className="toolbar"><div className="mini-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ism, telefon, login yoki rol..."/></div><Select value={role} onChange={setRole}><option>Barchasi</option>{state.roles.map(r=><option key={r.id}>{r.name}</option>)}</Select><Select value={branch} onChange={setBranch}><option value="Barchasi">Barcha filiallar</option>{state.branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</Select><Select value={status} onChange={setStatus}><option>Barchasi</option><option>Faol</option><option>Nofaol</option><option>Ta’tilda</option><option>Bloklangan</option><option>Arxiv</option></Select></div>
      <div className="responsive-table"><table><thead><tr><th>Xodim</th><th>Telefon</th><th>Rol</th><th>Filial</th><th>Ombor / Kassa</th><th>Bugungi savdo</th><th>Ish haqi turi</th><th>Smena</th><th>Oxirgi faollik</th><th>Status</th></tr></thead><tbody>{rows.map(e=><tr className="click-row" onClick={()=>onOpen(e)} key={e.id}><td><b>{e.name}</b><small>{e.position}</small></td><td>{e.phone||'—'}</td><td>{e.role}</td><td>{state.branches.find(b=>b.id===e.branchId)?.name||'—'}</td><td>{state.warehouses.find(w=>w.id===e.warehouseId)?.name||'—'} / {state.registers.find(r=>r.id===e.registerId)?.name||'—'}</td><td><Money value={e.sales}/></td><td>{e.salaryType}</td><td><Status>{e.shift}</Status></td><td>{e.lastActivity}</td><td><Status>{e.status}</Status></td></tr>)}</tbody></table>{!rows.length&&<Empty title="Xodim topilmadi" text="Qidiruv yoki filtrlarni o‘zgartiring."/>}</div>
    </Card>
  </>
}

function Roles({state,onNew,addRole,updateRole,toast}){
  const [selected,setSelected]=useState(state.roles[2]?.id||state.roles[0]?.id)
  const r=state.roles.find(x=>x.id===selected)||state.roles[0]
  const setPermission=(module,action,value)=>{if(!r||r.preset)return;const current=normalizePermission(r,module);updateRole(r.id,{permissions:{...r.permissions,[module]:{...current,[action]:value}}})}
  const setSensitive=(key,value)=>{if(!r||r.preset)return;updateRole(r.id,{permissions:{...r.permissions,_sensitive:{...(r.permissions?._sensitive||{}),[key]:value}}})}
  const clone=()=>{if(!r)return;const permissions=JSON.parse(JSON.stringify(r.permissions||{}));delete permissions.all;addRole({name:`${r.name} nusxasi`,scope:r.scope,permissions});toast(`${r.name} nusxasi yaratildi.`)}
  return <div className="roles-layout">
    <Card><div className="card-title"><div><b>Rollar</b><span>Preset yoki custom rol tanlang</span></div><button className="primary-glass-btn compact" onClick={onNew}><Plus/> Yangi rol</button></div><div className="role-list">{state.roles.map(x=><button className={selected===x.id?'active':''} key={x.id} onClick={()=>setSelected(x.id)}><span><ShieldCheck/><b>{x.name}</b><small>{state.employees.filter(e=>e.roleId===x.id).length} xodim · {x.preset?'Preset':'Custom'}</small></span></button>)}</div></Card>
    <Card><div className="card-title"><div><b>{r?.name} — Ruxsatlar</b><span>Modul → action → data scope</span></div><button className="soft-glass-btn compact" onClick={clone}><Copy/> Clone</button></div>{r?.preset&&<div className="info-note"><LockKeyhole/><span>Preset rol himoyalangan. Uni o‘zgartirish uchun Clone qiling va custom nusxasini tahrirlang.</span></div>}
      <div className="permission-table wide"><div className="permission-row head"><span>Modul</span>{actions.map(([,l])=><b key={l}>{l}</b>)}</div>{moduleDefs.map(([key,label])=>{const p=normalizePermission(r,key);return <div className="permission-row" key={key}><span>{label}</span>{actions.map(([a])=><button key={a} disabled={r?.preset} className={p[a]?'allowed':''} onClick={()=>setPermission(key,a,!p[a])}>{p[a]?<Check/>:'—'}</button>)}</div>})}</div>
      <div className="sensitive-box"><h3>Sensitive ma’lumotlar</h3><div className="sensitive-toggle-grid">{sensitive.map(([k,l])=><Toggle key={k} disabled={r?.preset} checked={!!(r?.permissions?.all||r?.permissions?._sensitive?.[k])} onChange={v=>setSensitive(k,v)} label={l}/>)}</div></div>
      <div className="scope-row"><span>Data scope</span>{r?.preset?<b>{scopeLabel(r?.scope)}</b>:<Select value={r?.scope||'branch'} onChange={v=>updateRole(r.id,{scope:v})}><option value="all">Barcha filiallar</option><option value="branch">Faqat o‘z filiali</option><option value="warehouse">Faqat o‘z ombori</option><option value="register">Faqat o‘z kassasi</option><option value="own">Faqat o‘z operatsiyalari</option></Select>}</div>
      <div className="role-preview"><Eye/><span><b>Role preview</b><small>Access yo‘q modul sidebar, flyout, qidiruv, notification va contextual actionlarda ko‘rinmasligi kerak; backend ham 403 bilan himoyalanadi.</small></span></div>
    </Card>
  </div>
}
function scopeLabel(s){return s==='all'?'Barcha filiallar':s==='branch'?'Faqat o‘z filiali':s==='warehouse'?'Faqat o‘z ombori':s==='register'?'Faqat o‘z kassasi':'Faqat o‘z operatsiyalari'}

function Shifts({state,onOpen,onClose}){
  const [q,setQ]=useState(''),[status,setStatus]=useState('Barchasi')
  const rows=state.shifts.filter(s=>(s.employee+' '+s.register).toLowerCase().includes(q.toLowerCase())&&(status==='Barchasi'||s.status===status))
  const late=state.shifts.filter(x=>minutes(x.openedAt)>minutes(x.scheduledStart)).length
  const diff=state.shifts.filter(x=>x.difference!==null&&x.difference!==0).length
  return <><div className="kpi-grid"><KPI label="Ochiq smenalar" value={state.shifts.filter(x=>x.status==='Ochiq').length} icon={<DoorOpen/>}/><KPI label="Yopilgan" value={state.shifts.filter(x=>x.status==='Yopilgan').length} icon={<DoorClosed/>}/><KPI label="Kech ochilgan" value={late} icon={<Clock/>}/><KPI label="Farqli smenalar" value={diff} icon={<AlertTriangle/>}/></div><Card><div className="card-title"><div><b>Smenalar</b><span>Opening cash → savdo → expected → actual → Z-report</span></div><button className="primary-glass-btn compact" onClick={onOpen}><DoorOpen/> Smena ochish</button></div><div className="toolbar"><div className="mini-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Xodim yoki kassa..."/></div><Select value={status} onChange={setStatus}><option>Barchasi</option><option>Ochiq</option><option>Yopilgan</option><option>Force closed</option></Select></div><div className="responsive-table"><table><thead><tr><th>Xodim</th><th>Kassa</th><th>Ochildi</th><th>Opening cash</th><th>Savdo</th><th>Cash In/Out</th><th>Expected</th><th>Actual</th><th>Farq</th><th>Status</th><th/></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td>{s.employee}</td><td>{s.register}</td><td>{s.openedAt}{minutes(s.openedAt)>minutes(s.scheduledStart)&&<small className="danger-text"> · kech</small>}</td><td><Money value={s.openingCash}/></td><td><Money value={s.sales}/></td><td>+<Money value={s.cashIn||0}/> / -<Money value={s.cashOut||0}/></td><td><Money value={s.expectedCash}/></td><td>{s.actualCash===null?'—':<Money value={s.actualCash}/>}</td><td>{s.difference===null?'—':<b className={s.difference?'danger-text':'positive-text'}><Money value={s.difference}/></b>}</td><td><Status>{s.status}</Status></td><td>{s.status==='Ochiq'&&<button className="soft-glass-btn compact" onClick={()=>onClose(s)}>Yopish</button>}</td></tr>)}</tbody></table>{!rows.length&&<Empty title="Smena topilmadi"/>}</div></Card></>
}

function Attendance({state,onAdd,onEdit}){
  const [q,setQ]=useState(''),[status,setStatus]=useState('Barchasi')
  const rows=state.attendance.filter(a=>{const e=state.employees.find(x=>x.id===a.employeeId);return (e?.name||'').toLowerCase().includes(q.toLowerCase())&&(status==='Barchasi'||a.status===status)})
  return <><div className="kpi-grid"><KPI label="Bugun kelgan" value={state.attendance.filter(a=>a.checkIn).length} icon={<CalendarCheck/>}/><KPI label="Kechikkan" value={state.attendance.filter(a=>a.status==='Kechikdi').length} icon={<Clock/>}/><KPI label="Yo‘q" value={state.attendance.filter(a=>a.status==='Yo‘q').length} icon={<Users/>}/><KPI label="Ta’tilda" value={state.attendance.filter(a=>a.status==='Ta’tilda').length} icon={<CalendarCheck/>}/></div><Card><div className="card-title"><div><b>Davomat</b><span>Check-in / Check-out, kechikish va ishlangan vaqt</span></div><button className="primary-glass-btn compact" onClick={onAdd}><Plus/> Davomat kiritish</button></div><div className="toolbar"><div className="mini-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Xodim..."/></div><Select value={status} onChange={setStatus}><option>Barchasi</option><option>Ishda</option><option>Kechikdi</option><option>Yo‘q</option><option>Ta’tilda</option><option>Kasallik</option><option>Dam olish</option><option>Erta ketdi</option></Select></div><div className="responsive-table"><table><thead><tr><th>Xodim</th><th>Sana</th><th>Reja</th><th>Check-in</th><th>Check-out</th><th>Kechikish</th><th>Ishlangan vaqt</th><th>Status</th><th/></tr></thead><tbody>{rows.map(a=>{const e=state.employees.find(x=>x.id===a.employeeId),late=minutes(a.checkIn)-minutes(a.scheduledStart);return <tr key={a.id}><td>{e?.name}</td><td>{a.date}</td><td>{a.scheduledStart}–{a.scheduledEnd}</td><td>{a.checkIn||'—'}</td><td>{a.checkOut||'—'}</td><td>{late>0?`${late} min`:'0 min'}</td><td>{a.checkOut&&a.checkIn?`${Math.max(0,minutes(a.checkOut)-minutes(a.checkIn))} min`:'Jarayonda'}</td><td><Status>{a.status}</Status></td><td><button className="icon-ghost" onClick={()=>onEdit(a)}><Edit3/></button></td></tr>})}</tbody></table>{!rows.length&&<Empty title="Davomat topilmadi"/>}</div></Card></>
}

function Payroll({state,onAdjust,onStatus}){
  const total=state.payroll.reduce((a,p)=>a+p.total,0)
  const unpaid=state.payroll.filter(p=>p.status!=='To‘landi').reduce((a,p)=>a+p.total,0)
  return <><div className="kpi-grid"><KPI label="Shu oy hisoblangan" value={<Money value={total}/>} icon={<WalletCards/>}/><KPI label="To‘lanmagan" value={<Money value={unpaid}/>} icon={<Clock/>}/><KPI label="Bonuslar" value={<Money value={state.payroll.reduce((a,p)=>a+p.bonus,0)}/>} icon={<Percent/>}/><KPI label="Ushlab qolish" value={<Money value={state.payroll.reduce((a,p)=>a+p.deduction,0)}/>} icon={<WalletCards/>}/></div><Card><div className="card-title"><b>Ish haqi / KPI</b><span>Qoralama → Tekshiruvda → Tasdiqlandi → To‘landi</span></div><div className="responsive-table"><table><thead><tr><th>Xodim</th><th>Davr</th><th>Oylik</th><th>Komissiya</th><th>Bonus</th><th>Ushlab qolish</th><th>Jami</th><th>Status</th><th>Amallar</th></tr></thead><tbody>{state.payroll.map(p=><tr key={p.id}><td>{p.employee}</td><td>{p.period}</td><td><Money value={p.base}/></td><td><Money value={p.commission}/></td><td><Money value={p.bonus}/></td><td><Money value={p.deduction}/></td><td><b><Money value={p.total}/></b></td><td><Status>{p.status}</Status></td><td><div className="row-actions-inline"><button className="soft-glass-btn compact" onClick={()=>onAdjust(state.employees.find(e=>e.id===p.employeeId))}>Bonus / Ushlab qolish</button><button className="soft-glass-btn compact" onClick={()=>onStatus(p)}>Status / To‘lov</button></div></td></tr>)}</tbody></table></div></Card><Card><div className="card-title"><b>KPI qoidalari</b></div><div className="kpi-rule-grid">{['Savdo summasi','Chek soni','O‘rtacha chek','Qaytarish %','Chegirma %','Davomat','Stock accuracy'].map(x=><div key={x}><b>{x}</b><small>Rol yoki xodim bo‘yicha target beriladi</small></div>)}</div></Card></>
}

function Activity({state}){
  const [q,setQ]=useState(''),[module,setModule]=useState('Barchasi'),[severity,setSeverity]=useState('Barchasi')
  const rows=state.activity.filter(a=>(a.employee+' '+a.action+' '+a.entity).toLowerCase().includes(q.toLowerCase())&&(module==='Barchasi'||a.module===module)&&(severity==='Barchasi'||a.severity===severity))
  return <Card><div className="card-title"><div><b>Faoliyat / Audit</b><span>Sensitive operatsiyalar hard delete qilinmaydi.</span></div></div><div className="toolbar"><div className="mini-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Xodim, action yoki document..."/></div><Select value={module} onChange={setModule}><option>Barchasi</option>{[...new Set(state.activity.map(a=>a.module))].map(m=><option key={m}>{m}</option>)}</Select><Select value={severity} onChange={setSeverity}><option>Barchasi</option><option>info</option><option>warning</option><option>danger</option></Select></div><div className="responsive-table"><table><thead><tr><th>Sana / vaqt</th><th>Xodim</th><th>Modul</th><th>Action</th><th>Entity</th><th>Sabab</th><th>Severity</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{a.date} {a.time}</td><td>{a.employee}</td><td>{a.module}</td><td>{a.action}</td><td>{a.entity||'—'}</td><td>{a.reason||'—'}</td><td><Status>{a.severity}</Status></td></tr>)}</tbody></table>{!rows.length&&<Empty title="Activity topilmadi"/>}</div></Card>
}

function EmployeeModal({state,employee,onClose,onSave}){
  const defaultRole=state.roles[1]?.id||state.roles[0]?.id||''
  const [f,setF]=useState(employee?{...employee}:{name:'',phone:'',login:'',email:'',roleId:defaultRole,branchId:state.branches[0]?.id||'',warehouseId:state.warehouses[0]?.id||'',registerId:'',position:'',salaryType:'Oylik',baseSalary:0,commission:0,status:'Faol',startDate:new Date().toISOString().slice(0,10),temporaryPassword:`Zx${Math.floor(100000+Math.random()*899999)}!`,forcePasswordChange:true,note:'',documents:[]})
  const [error,setError]=useState('')
  const submit=()=>{if(!f.name?.trim())return setError('F.I.Sh. kiriting.');if(!f.login?.trim())return setError('Login kiriting.');const dup=state.employees.find(e=>e.id!==employee?.id&&((f.phone&&e.phone===f.phone)||(f.login&&e.login===f.login)||(f.email&&e.email===f.email)));if(dup)return setError(`Bu telefon/login/email boshqa xodimda mavjud: ${dup.name}`);onSave({...f,name:f.name.trim(),login:f.login.trim(),baseSalary:n(f.baseSalary),commission:n(f.commission)})}
  return <Modal open onClose={onClose} title={employee?'Xodimni tahrirlash':'Yangi xodim'} eyebrow="EMPLOYEE" size="xl" footer={<><button className="secondary-glass-btn" onClick={onClose}>Bekor</button><button className="primary-glass-btn" onClick={submit}><Check/> {employee?'Saqlash':'Xodim yaratish'}</button></>}><div className="form-grid two"><Field label="F.I.Sh. *" error={error}><Input autoFocus value={f.name} onChange={v=>{setF({...f,name:v});setError('')}}/></Field><Field label="Telefon"><Input value={f.phone} onChange={v=>{setF({...f,phone:v});setError('')}}/></Field><Field label="Login *"><Input value={f.login} onChange={v=>{setF({...f,login:v});setError('')}}/></Field><Field label="Email"><Input value={f.email||''} onChange={v=>{setF({...f,email:v});setError('')}}/></Field><Field label="Rol"><Select value={f.roleId} onChange={v=>setF({...f,roleId:v})}>{state.roles.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</Select></Field><Field label="Lavozim"><Input value={f.position} onChange={v=>setF({...f,position:v})}/></Field><Field label="Filial"><Select value={f.branchId} onChange={v=>setF({...f,branchId:v})}>{state.branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</Select></Field><Field label="Ombor"><Select value={f.warehouseId} onChange={v=>setF({...f,warehouseId:v})}>{state.warehouses.map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</Select></Field><Field label="Kassa"><Select value={f.registerId||''} onChange={v=>setF({...f,registerId:v})}><option value="">Biriktirilmagan</option>{state.registers.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</Select></Field><Field label="Ish boshlash sanasi"><Input type="date" value={f.startDate||''} onChange={v=>setF({...f,startDate:v})}/></Field><Field label="Ish haqi turi"><Select value={f.salaryType} onChange={v=>setF({...f,salaryType:v})}><option>Oylik</option><option>Soatlik</option><option>Savdodan %</option><option>Oylik + foiz</option><option>Custom</option></Select></Field><Field label="Status"><Select value={f.status} onChange={v=>setF({...f,status:v})}><option>Faol</option><option>Nofaol</option><option>Ta’tilda</option><option>Bloklangan</option><option>Arxiv</option></Select></Field><Field label="Oylik"><Input type="number" min="0" value={f.baseSalary} onChange={v=>setF({...f,baseSalary:v})}/></Field><Field label="Komissiya %"><Input type="number" min="0" value={f.commission} onChange={v=>setF({...f,commission:v})}/></Field><Field label="Izoh" className="span-2"><Input value={f.note||''} onChange={v=>setF({...f,note:v})}/></Field></div>{!employee&&<div className="info-note"><LockKeyhole/><span>Vaqtinchalik parol: <b>{f.temporaryPassword}</b>. Birinchi kirishda almashtirish talab qilinadi.</span></div>}</Modal>
}

function EmployeeDetail({state,employee,onClose,onEdit,onUpdate,onBlock}){
  const [tab,setTab]=useState('Umumiy'),role=state.roles.find(r=>r.id===employee.roleId)
  const shifts=state.shifts.filter(x=>x.employeeId===employee.id),attendance=state.attendance.filter(x=>x.employeeId===employee.id),payroll=state.payroll.filter(x=>x.employeeId===employee.id),activity=state.activity.filter(x=>x.employee===employee.name),sales=state.sales.filter(x=>x.cashier===employee.name||x.employeeId===employee.id)
  const docRef=useRef(null)
  const addDoc=file=>{if(!file)return;onUpdate(employee.id,{documents:[...(employee.documents||[]),{id:`edoc-${Date.now()}`,name:file.name,size:file.size,type:file.type,addedAt:new Date().toLocaleDateString('uz-UZ')} ]})}
  return <Drawer onClose={onClose} title={employee.name} eyebrow="XODIM" subtitle={`${employee.role} · ${employee.phone||'telefon yo‘q'}`} size="lg" actions={<><button className="secondary-glass-btn" onClick={()=>onEdit(employee)}><Edit3/> Tahrirlash</button><button className={employee.status==='Bloklangan'?'primary-glass-btn':'danger-glass-btn'} onClick={()=>onBlock(employee)}>{employee.status==='Bloklangan'?<Check/>:<Ban/>}{employee.status==='Bloklangan'?' Faollashtirish':' Bloklash'}</button></>}>
    <div className="drawer-tabs">{['Umumiy','Ruxsatlar','Smenalar','Davomat','Savdo / Operatsiyalar','Ish haqi / KPI','Hujjatlar','Activity'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
    {tab==='Umumiy'&&<><div className="detail-grid"><div><span>Login</span><b>{employee.login}</b></div><div><span>Rol</span><b>{employee.role}</b></div><div><span>Filial</span><b>{state.branches.find(b=>b.id===employee.branchId)?.name||'—'}</b></div><div><span>Ombor</span><b>{state.warehouses.find(w=>w.id===employee.warehouseId)?.name||'—'}</b></div><div><span>Kassa</span><b>{state.registers.find(r=>r.id===employee.registerId)?.name||'—'}</b></div><div><span>Status</span><b>{employee.status}</b></div><div><span>Bugungi savdo</span><b><Money value={employee.sales}/></b></div><div><span>Ish haqi</span><b>{employee.salaryType}</b></div><div><span>Ish boshlagan sana</span><b>{employee.startDate||'—'}</b></div><div><span>Oxirgi faollik</span><b>{employee.lastActivity||'—'}</b></div></div>{employee.note&&<div className="detail-section"><h3>Izoh</h3><p>{employee.note}</p></div>}</>}
    {tab==='Ruxsatlar'&&<div className="detail-section"><div className="permission-preview"><ShieldCheck/><div><b>{role?.name}</b><small>Scope: {scopeLabel(role?.scope)}</small></div></div><div className="permission-chip-grid">{moduleDefs.map(([k,l])=>{const p=normalizePermission(role,k);return <span className={p.view?'active':''} key={k}>{l}: {p.view?'Ko‘radi':'Yopiq'}</span>})}</div></div>}
    {tab==='Smenalar'&&<MiniTable empty="Smena tarixi yo‘q" headers={['Kassa','Ochildi','Yopildi','Savdo','Expected','Farq','Status']} rows={shifts.map(s=>[s.register,s.openedAt,s.closedAt||'—',<Money value={s.sales}/>,<Money value={s.expectedCash}/>,s.difference===null?'—':<Money value={s.difference}/>,<Status>{s.status}</Status>])}/>}
    {tab==='Davomat'&&<MiniTable empty="Davomat tarixi yo‘q" headers={['Sana','Check-in','Check-out','Kechikish','Status']} rows={attendance.map(a=>[a.date,a.checkIn||'—',a.checkOut||'—',`${Math.max(0,minutes(a.checkIn)-minutes(a.scheduledStart))} min`,<Status>{a.status}</Status>])}/>}
    {tab==='Savdo / Operatsiyalar'&&<><div className="detail-grid"><div><span>Savdolar</span><b>{sales.length} ta</b></div><div><span>Jami savdo</span><b><Money value={sales.reduce((a,x)=>a+x.amount,0)}/></b></div><div><span>Audit actionlar</span><b>{activity.length} ta</b></div><div><span>Qaytarishlar</span><b>{sales.filter(s=>s.status==='Qaytarildi').length} ta</b></div></div><MiniTable empty="Operatsiya yo‘q" headers={['Sana','Modul','Action','Entity']} rows={activity.slice(0,12).map(a=>[`${a.date} ${a.time}`,a.module,a.action,a.entity||'—'])}/></>}
    {tab==='Ish haqi / KPI'&&<><div className="detail-grid"><div><span>Maosh turi</span><b>{employee.salaryType}</b></div><div><span>Oylik</span><b><Money value={employee.baseSalary}/></b></div><div><span>Komissiya</span><b>{employee.commission||0}%</b></div><div><span>Payroll yozuvlari</span><b>{payroll.length} ta</b></div></div><MiniTable empty="Payroll tarixi yo‘q" headers={['Davr','Jami','Bonus','Ushlab qolish','Status']} rows={payroll.map(p=>[p.period,<Money value={p.total}/>,<Money value={p.bonus}/>,<Money value={p.deduction}/>,<Status>{p.status}</Status>])}/></>}
    {tab==='Hujjatlar'&&<div className="detail-section"><div className="card-title"><div><b>Hujjatlar</b><span>Shartnoma, ID nusxa va boshqa xodim hujjatlari</span></div><><input ref={docRef} type="file" hidden onChange={e=>addDoc(e.target.files?.[0])}/><button className="soft-glass-btn compact" onClick={()=>docRef.current?.click()}><Upload/> Fayl qo‘shish</button></></div>{(employee.documents||[]).map(d=><div className="line-summary" key={d.id}><span><b>{d.name}</b><small>{d.addedAt} · {Math.ceil((d.size||0)/1024)} KB</small></span><FileText/></div>)}{!(employee.documents||[]).length&&<Empty icon={<FileText/>} title="Hujjat yo‘q" text="Xodimga hali fayl biriktirilmagan."/>}</div>}
    {tab==='Activity'&&<MiniTable empty="Activity yo‘q" headers={['Sana/vaqt','Modul','Action','Entity','Sabab']} rows={activity.map(a=>[`${a.date} ${a.time}`,a.module,a.action,a.entity||'—',a.reason||'—'])}/>} 
  </Drawer>
}

function MiniTable({headers,rows,empty}){return <div className="responsive-table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty title={empty}/>}</div>}

function RoleModal({state,onClose,onSave}){
  const [name,setName]=useState(''),[scope,setScope]=useState('branch'),[permissions,setPermissions]=useState({sales:{view:true,create:true,edit:false,approve:false,reverse:false,export:false,print:true},pos:{view:true,create:true,edit:false,approve:false,reverse:false,export:false,print:true}}),[error,setError]=useState('')
  const toggle=(key)=>{const current=permissions[key]?.view;setPermissions({...permissions,[key]:Object.fromEntries(actions.map(([a])=>[a,a==='view'?!current:!current&&['create','print'].includes(a)]))})}
  const submit=()=>{if(!name.trim())return setError('Rol nomini kiriting.');if(state.roles.some(r=>r.name.toLowerCase()===name.trim().toLowerCase()))return setError('Bu nomdagi rol mavjud.');onSave({name:name.trim(),scope,permissions})}
  return <Modal open onClose={onClose} title="Yangi rol" eyebrow="ROLE & PERMISSIONS" size="lg" footer={<><button className="secondary-glass-btn" onClick={onClose}>Bekor</button><button className="primary-glass-btn" onClick={submit}>Rol yaratish</button></>}><Field label="Rol nomi" error={error}><Input value={name} onChange={v=>{setName(v);setError('')}}/></Field><Field label="Data scope"><Select value={scope} onChange={setScope}><option value="all">Barcha filiallar</option><option value="branch">Faqat o‘z filiali</option><option value="warehouse">Faqat o‘z ombori</option><option value="register">Faqat o‘z kassasi</option><option value="own">Faqat o‘z operatsiyalari</option></Select></Field><div className="toggle-stack">{moduleDefs.map(([k,l])=><Toggle key={k} checked={!!permissions[k]?.view} onChange={()=>toggle(k)} label={l}/>)}</div></Modal>
}

function ShiftOpenModal({state,onClose,onSave}){
  const freeRegisters=state.registers.filter(r=>!state.shifts.some(s=>s.registerId===r.id&&s.status==='Ochiq'))
  const [employeeId,setEmployee]=useState(state.employees.find(e=>e.status==='Faol')?.id||''),[registerId,setRegister]=useState(freeRegisters[0]?.id||''),[openingCash,setCash]=useState(0),[error,setError]=useState('')
  const submit=()=>{if(!employeeId||!registerId)return setError('Xodim va bo‘sh kassani tanlang.');onSave({employeeId,registerId,openingCash:n(openingCash)})}
  return <Modal open onClose={onClose} title="Smena ochish" eyebrow="SHIFT" footer={<><button className="secondary-glass-btn" onClick={onClose}>Bekor</button><button className="primary-glass-btn" onClick={submit}>Ochish</button></>}><Field label="Xodim"><Select value={employeeId} onChange={setEmployee}>{state.employees.filter(e=>e.status==='Faol').map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</Select></Field><Field label="Kassa"><Select value={registerId} onChange={setRegister}><option value="">Tanlang</option>{freeRegisters.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</Select></Field><Field label="Boshlang‘ich naqd"><Input type="number" min="0" value={openingCash} onChange={setCash}/></Field>{error&&<div className="inline-alert danger"><AlertTriangle/>{error}</div>}</Modal>
}
function ShiftCloseModal({shift,onClose,onSave}){
  const [actualCash,setActual]=useState(shift?.expectedCash||0),[reason,setReason]=useState(''),[error,setError]=useState('')
  const difference=n(actualCash)-n(shift?.expectedCash),early=minutes(new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false}))<18*60
  const submit=()=>{if((difference!==0||early)&&!reason.trim())return setError(difference!==0?'Kassa farqi bo‘lsa sabab majburiy.':'Smena ish vaqtidan oldin yopilyapti. Sabab yozing.');onSave({actualCash:n(actualCash),reason:reason.trim()})}
  return <Modal open={!!shift} onClose={onClose} title="Smena yopish" eyebrow="SHIFT CLOSE" subtitle={`Expected cash: ${Number(shift?.expectedCash||0).toLocaleString('uz-UZ')} so‘m`} footer={<><button className="secondary-glass-btn" onClick={onClose}>Bekor</button><button className="primary-glass-btn" onClick={submit}>Yopish</button></>}><div className="detail-grid"><div><span>Expected</span><b><Money value={shift?.expectedCash}/></b></div><div><span>Real</span><b><Money value={actualCash}/></b></div><div><span>Farq</span><b className={difference?'danger-text':'positive-text'}><Money value={difference}/></b></div><div><span>Holat</span><b>{early?'Erta yopilmoqda':'Normal'}</b></div></div><Field label="Real sanalgan naqd"><Input type="number" value={actualCash} onChange={setActual}/></Field><Field label="Sabab / izoh"><Input value={reason} onChange={v=>{setReason(v);setError('')}}/></Field>{error&&<div className="inline-alert danger"><AlertTriangle/>{error}</div>}</Modal>
}
function AttendanceModal({state,row,onClose,onSave}){
  const [f,setF]=useState(row?{...row}:{employeeId:state.employees[0]?.id||'',date:new Date().toISOString().slice(0,10),scheduledStart:'09:00',scheduledEnd:'18:00',checkIn:'09:00',checkOut:'',status:'Ishda',reason:''})
  const submit=()=>onSave({...f,id:row?.id,date:f.date?f.date.split('-').reverse().join('.'):f.date})
  return <Modal open onClose={onClose} title={row?'Davomatni tuzatish':'Davomat kiritish'} eyebrow="ATTENDANCE" footer={<><button className="secondary-glass-btn" onClick={onClose}>Bekor</button><button className="primary-glass-btn" onClick={submit}><SaveIcon/> Saqlash</button></>}><div className="form-grid two"><Field label="Xodim"><Select value={f.employeeId} onChange={v=>setF({...f,employeeId:v})}>{state.employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</Select></Field><Field label="Sana"><Input type="date" value={String(f.date||'').includes('.')?f.date.split('.').reverse().join('-'):f.date} onChange={v=>setF({...f,date:v})}/></Field><Field label="Reja boshlanish"><Input type="time" value={f.scheduledStart} onChange={v=>setF({...f,scheduledStart:v})}/></Field><Field label="Reja tugash"><Input type="time" value={f.scheduledEnd} onChange={v=>setF({...f,scheduledEnd:v})}/></Field><Field label="Check-in"><Input type="time" value={f.checkIn} onChange={v=>setF({...f,checkIn:v})}/></Field><Field label="Check-out"><Input type="time" value={f.checkOut} onChange={v=>setF({...f,checkOut:v})}/></Field><Field label="Status"><Select value={f.status} onChange={v=>setF({...f,status:v})}><option>Ishda</option><option>Kechikdi</option><option>Yo‘q</option><option>Ta’tilda</option><option>Kasallik</option><option>Dam olish</option><option>Erta ketdi</option></Select></Field><Field label="Correction sababi"><Input value={f.reason||''} onChange={v=>setF({...f,reason:v})}/></Field></div></Modal>
}
const SaveIcon=Check
function PayrollAdjust({employee,onClose,onSave}){
  const [type,setType]=useState('bonus'),[amount,setAmount]=useState(0),[reason,setReason]=useState(''),[error,setError]=useState('')
  const submit=()=>{if(n(amount)<=0)return setError('Summani kiriting.');if(!reason.trim())return setError('Sabab majburiy.');onSave({employeeId:employee.id,type,amount:n(amount),reason:reason.trim()})}
  return <Modal open={!!employee} onClose={onClose} title="Payroll adjustment" eyebrow="ISH HAQI" subtitle={employee?.name} footer={<><button className="secondary-glass-btn" onClick={onClose}>Bekor</button><button className="primary-glass-btn" onClick={submit}>Saqlash</button></>}><Field label="Turi"><Select value={type} onChange={setType}><option value="bonus">+ Bonus</option><option value="deduction">Ushlab qolish</option></Select></Field><Field label="Summa"><Input type="number" min="0" value={amount} onChange={setAmount}/></Field><Field label="Sabab"><Input value={reason} onChange={v=>{setReason(v);setError('')}}/></Field>{error&&<div className="inline-alert danger"><AlertTriangle/>{error}</div>}</Modal>
}
function PayrollStatusModal({state,payroll,onClose,onSave}){
  const accounts=[...state.registers.map(r=>r.name),...state.accounts.map(a=>a.name)]
  const [status,setStatus]=useState(payroll.status),[account,setAccount]=useState(state.accounts[0]?.name||state.registers[0]?.name||''),[method,setMethod]=useState('Bank')
  return <Modal open onClose={onClose} title="Payroll status / to‘lov" eyebrow="PAYROLL" subtitle={`${payroll.employee} · ${payroll.period}`} footer={<><button className="secondary-glass-btn" onClick={onClose}>Bekor</button><button className="primary-glass-btn" onClick={()=>onSave({payrollId:payroll.id,status,account,method})}><Check/> Saqlash</button></>}><div className="detail-grid"><div><span>Jami</span><b><Money value={payroll.total}/></b></div><div><span>Hozirgi status</span><b>{payroll.status}</b></div></div><Field label="Yangi status"><Select value={status} onChange={setStatus}><option>Qoralama</option><option>Tekshiruvda</option><option>Tasdiqlandi</option><option>To‘landi</option></Select></Field>{status==='To‘landi'&&<div className="form-grid two"><Field label="Hisob / Kassa"><Select value={account} onChange={setAccount}>{accounts.map(a=><option key={a}>{a}</option>)}</Select></Field><Field label="To‘lov usuli"><Select value={method} onChange={setMethod}><option>Bank</option><option>Naqd</option><option>Karta</option></Select></Field></div>}</Modal>
}
