import React,{useEffect,useMemo,useRef,useState} from 'react'
import {ArrowLeft,Search,ScanLine,Bookmark,Users,Minus,Plus,Trash2,CreditCard,Banknote,QrCode,ReceiptText,X,Check,Maximize2,Grid3X3,List,FolderOpen,Gift,Clock3,Warehouse,WalletCards} from 'lucide-react'
import {useNavigate} from 'react-router-dom'
import {useApp} from '../state/AppContext'
import {Money,Modal,Field,Input,Select,Segmented,Toast} from '../components/UI'

const warehouseStock=(state,warehouseId,productId)=>state.warehouseStocks.find(x=>x.warehouseId===warehouseId&&x.productId===productId)||{qty:0,reserved:0}

export default function PosTerminal(){
  const {state,createSale,saveCart,removeSavedCart,currentEmployee}=useApp(),nav=useNavigate();const searchRef=useRef(null)
  const [query,setQuery]=useState(''),[cat,setCat]=useState('Barchasi'),[cart,setCart]=useState([]),[customerId,setCustomerId]=useState(''),[discount,setDiscount]=useState(0),[pay,setPay]=useState(false),[saved,setSaved]=useState(false),[scanner,setScanner]=useState(false),[scannerCode,setScannerCode]=useState(''),[view,setView]=useState('grid'),[toast,setToast]=useState(''),[warehouseId,setWarehouseId]=useState(state.settings.defaultWarehouseId),[registerId,setRegisterId]=useState(state.settings.defaultRegisterId),[priceType,setPriceType]=useState(state.settings.pos.defaultPriceType||'retail')
  useEffect(()=>{if(state.settings.pos.autoFocus)searchRef.current?.focus()},[state.settings.pos.autoFocus])
  useEffect(()=>{if(!state.settings.pos.shortcuts)return;const fn=e=>{if(e.key==='F2'){e.preventDefault();searchRef.current?.focus()}if(e.key==='F8'&&cart.length&&(!state.settings.pos.customerRequired||customerId)){e.preventDefault();setPay(true)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'&&state.settings.pos.saveCart){e.preventDefault();doSave()}if(e.key==='Escape'&&pay)setPay(false)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[state.settings.pos.shortcuts,state.settings.pos.saveCart,state.settings.pos.customerRequired,cart.length,customerId,pay])
  const customer=state.customers.find(c=>c.id===customerId)
  useEffect(()=>{if(customer?.priceType)setPriceType(customer.priceType)},[customerId])
  const categories=['Barchasi',...new Set(state.products.map(p=>p.category))]
  const availableOf=p=>{const s=warehouseStock(state,warehouseId,p.id);return Math.max(0,(s.qty||0)-(s.reserved||0))}
  const filtered=state.products.filter(p=>p.active&&(cat==='Barchasi'||p.category===cat)&&(p.name+' '+p.sku+' '+p.barcode).toLowerCase().includes(query.toLowerCase()))
  const priceFor=p=>priceType==='wholesale'?p.wholesale:priceType==='vip'?p.vip:priceType==='promo'?p.promo:p.price
  useEffect(()=>setCart(c=>c.map(x=>({...x,price:priceFor(x),stock:availableOf(x)})).filter(x=>x.stock>0)),[priceType,warehouseId])
  const add=p=>{const available=availableOf(p);if(available<=0)return;setCart(c=>{const found=c.find(x=>x.id===p.id);if(found)return c.map(x=>x.id===p.id?{...x,stock:available,qty:Math.min(x.qty+1,available)}:x);return [...c,{...p,stock:available,qty:1,price:priceFor(p)}]})}
  const addFromSearch=()=>{const code=query.trim();if(!code)return;const p=state.products.find(x=>x.active&&(x.barcode===code||x.sku.toLowerCase()===code.toLowerCase()));if(!p){if(state.settings.pos.unknownBarcode==='create'){setQuery('');nav(`/products?create=1&barcode=${encodeURIComponent(code)}`)}else setToast('Barcode yoki SKU topilmadi.');return}if(availableOf(p)<=0){setToast('Bu omborda mahsulot sotish uchun mavjud emas.');return}add(p);setQuery('');setToast(`${p.name} skaner orqali savatga qo‘shildi.`)}
  const qty=(id,d)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(1,Math.min(availableOf(x),x.qty+d)),stock:availableOf(x)}:x))
  const subtotal=cart.reduce((a,x)=>a+x.price*x.qty,0),discountValue=Math.round(subtotal*(+discount||0)/100),total=Math.max(0,subtotal-discountValue)
  const doSave=()=>{if(!state.settings.pos.saveCart||!cart.length)return;saveCart({items:cart,customerId,discount,warehouseId,registerId,priceType});setCart([]);setCustomerId('');setDiscount(0);setToast('Savdo vaqtincha saqlandi.')}
  const scan=()=>{const code=scannerCode.trim();const p=state.products.find(x=>x.barcode===code||x.sku===code);if(p&&availableOf(p)>0){add(p);setScanner(false);setScannerCode('');setToast(`${p.name} savatga qo‘shildi.`)}else if(p)setToast('Bu omborda mahsulot sotish uchun mavjud emas.');else if(state.settings.pos.unknownBarcode==='create'){setScanner(false);nav(`/products?create=1&barcode=${encodeURIComponent(code)}`)}else setToast('Barcode topilmadi.')}
  const restoreSaved=x=>{setWarehouseId(x.warehouseId||state.settings.defaultWarehouseId);setRegisterId(x.registerId||state.settings.defaultRegisterId);setPriceType(x.priceType||state.settings.pos.defaultPriceType||'retail');setCart(x.items||[]);setCustomerId(x.customerId||'');setDiscount(x.discount||0);removeSavedCart(x.id);setSaved(false);setToast('Saqlangan savdo tiklandi.')}

  return <div className="pos-shell">
    <header className="pos-top liquid-panel"><button className="pos-back" onClick={()=>nav('/sales')}><ArrowLeft/> Savdo</button><div className="pos-meta"><span><Clock3/> {new Date().toLocaleTimeString('uz-UZ',{hour:'2-digit',minute:'2-digit'})}</span><div className="pos-meta-select"><Warehouse/><Select value={warehouseId} onChange={v=>{if(cart.length){setToast('Omborni almashtirishdan oldin savatni saqlang yoki tozalang.');return}setWarehouseId(v)}}>{state.warehouses.filter(w=>w.status==='Faol').map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</Select></div><div className="pos-meta-select"><WalletCards/><Select value={registerId} onChange={setRegisterId}>{state.registers.filter(r=>r.status==='Faol').map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</Select></div><span>{currentEmployee?.name||'User'}</span></div><div className="pos-top-actions"><button onClick={()=>document.documentElement.requestFullscreen?.()}><Maximize2/></button><button onClick={()=>nav('/sales')}><X/></button></div></header>
    <main className="pos-main"><section className="pos-products liquid-card"><div className="pos-search-row"><div className="pos-search"><Search/><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addFromSearch()} placeholder="Mahsulot nomi, SKU yoki barcode..."/><kbd>F2</kbd></div><Select value={priceType} onChange={setPriceType} className="pos-price-select">{state.priceTypes.filter(x=>x.status==='Faol').map(x=><option value={x.id} key={x.id}>{x.name} narx</option>)}</Select><button className="soft-glass-btn" onClick={()=>setScanner(true)}><ScanLine/> Skaner</button><button className="icon-btn" onClick={()=>setView(v=>v==='grid'?'list':'grid')}>{view==='grid'?<List/>:<Grid3X3/>}</button></div><div className="pos-categories">{categories.map(c=><button key={c} className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div><div className={view==='grid'?"product-grid":"product-list"}>{filtered.map(p=>{const available=availableOf(p);return <button key={p.id} className={`pos-product ${available<=0?'disabled':''}`} disabled={available<=0} onClick={()=>add(p)}><span className="pos-product-thumb">{p.image?<img src={p.image} alt=""/>:p.name.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase()}</span><div><b>{p.name}</b><small>{p.category} · {p.unit}</small><strong><Money value={priceFor(p)}/></strong><em className={available<=p.minStock?'low':''}>{available} sotish mumkin</em></div></button>})}</div></section>
      <aside className="pos-cart liquid-card"><div className="cart-head"><div><h2>Savat</h2><span>{cart.reduce((a,x)=>a+x.qty,0)} ta mahsulot</span></div><div>{state.settings.pos.saveCart&&<><button className="icon-btn" onClick={()=>setSaved(true)} title="Saqlangan savdolar"><FolderOpen/></button><button className="icon-btn" onClick={doSave} disabled={!cart.length} title="Savatni vaqtincha saqlash"><Bookmark/></button></>}</div></div><div className="customer-select-wrap"><Users/><Select value={customerId} onChange={setCustomerId}><option value="">Chakana mijoz</option>{state.customers.filter(c=>c.status==='Faol').map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</Select></div>{customer&&<div className="customer-bonus-strip"><span><Gift/> Bonus: <b><Money value={customer.bonusBalance}/></b></span><span>Yig‘iladi: <b>+{customer.earnBonus?Math.round(total*(customer.bonusRate||0)/100):0} so‘m</b></span></div>}<div className="cart-lines">{!cart.length&&<div className="cart-empty"><ReceiptText/><b>Savat bo‘sh</b><span>Mahsulot kartasini bosing yoki barcode skaner qiling.</span></div>}{cart.map(x=><div className="cart-line" key={x.id}><span className="line-thumb">{x.name[0]}</span><div className="line-info"><b>{x.name}</b><small><Money value={x.price}/></small></div><div className="qty"><button onClick={()=>qty(x.id,-1)}><Minus/></button><b>{x.qty}</b><button onClick={()=>qty(x.id,1)} disabled={x.qty>=availableOf(x)}><Plus/></button></div><strong><Money value={x.price*x.qty}/></strong><button className="remove" onClick={()=>setCart(c=>c.filter(i=>i.id!==x.id))}><Trash2/></button></div>)}</div><div className="cart-footer"><label className="discount-row"><span>Chegirma</span><Input type="number" min="0" max={state.settings.pos.maxCashierDiscount||100} value={discount} onChange={v=>setDiscount(Math.min(+v||0,state.settings.pos.maxCashierDiscount||100))}/><b>%</b></label><p><span>Oraliq summa</span><b><Money value={subtotal}/></b></p>{discountValue>0&&<p><span>Chegirma</span><b>- <Money value={discountValue}/></b></p>}<div className="grand"><span>Jami</span><b><Money value={total}/></b></div>{state.settings.pos.customerRequired&&!customerId&&<small className="pos-required-note">To‘lov uchun mijoz tanlash majburiy.</small>}<button className="primary-glass-btn pos-pay" disabled={!cart.length||(state.settings.pos.customerRequired&&!customerId)} onClick={()=>setPay(true)}><CreditCard/> To‘lov {state.settings.pos.shortcuts&&<kbd>F8</kbd>}</button></div></aside>
    </main>
    <PaymentModal open={pay} onClose={()=>setPay(false)} total={total} customer={customer} onDone={({payments,bonusUsed})=>{createSale({items:cart,total,customerId,payments,discount:discountValue,bonusUsed,registerId,warehouseId});setCart([]);setDiscount(0);setCustomerId('');setPay(false);setToast('Savdo muvaffaqiyatli yakunlandi.')}}/>
    <Modal open={scanner} onClose={()=>setScanner(false)} title="Barcode skaner" eyebrow="SKANER" subtitle="USB skaner kodi shu inputga yozadi yoki kodni qo‘lda kiriting." footer={<><button className="secondary-glass-btn" onClick={()=>setScanner(false)}>Bekor</button><button className="primary-glass-btn" onClick={scan}><ScanLine/> Topish</button></>}><Field label="Barcode / SKU"><Input autoFocus value={scannerCode} onChange={setScannerCode} placeholder="544900000001"/></Field></Modal>
    <Modal open={saved} onClose={()=>setSaved(false)} title="Saqlangan savdolar" eyebrow="PARKED SALES" subtitle="Vaqtincha saqlangan savatni davom ettiring." size="lg"><div className="saved-cart-list">{!state.savedCarts.length&&<div className="cart-empty"><Bookmark/><b>Saqlangan savdo yo‘q</b></div>}{state.savedCarts.map(x=><button key={x.id} onClick={()=>restoreSaved(x)}><span><b>{x.items?.length||0} xil mahsulot</b><small>{new Date(x.createdAt).toLocaleString('uz-UZ')} · {state.warehouses.find(w=>w.id===x.warehouseId)?.name||'Ombor'}</small></span><strong><Money value={(x.items||[]).reduce((a,i)=>a+i.price*i.qty,0)}/></strong></button>)}</div></Modal>
    <Toast message={toast} onDone={()=>setToast('')}/>
  </div>
}

function PaymentModal({open,onClose,total,customer,onDone}){
  const {state}=useApp()
  const methods=state.paymentMethods.filter(x=>x.enabled&&x.posVisible&&x.type!=='bonus'&&(state.settings.pos.creditEnabled||x.type!=='credit')&&(customer||x.type!=='credit')).map(x=>x.name)
  const defaultMethod=methods.includes('Naqd')?'Naqd':methods[0]||'Naqd'
  const [mode,setMode]=useState('single'),[single,setSingle]=useState(defaultMethod),[received,setReceived]=useState(total),[bonusUsed,setBonusUsed]=useState(0),[lines,setLines]=useState([{method:defaultMethod,amount:total}])
  useEffect(()=>{if(open){setReceived(total);setBonusUsed(0);setLines([{method:defaultMethod,amount:total}]);setSingle(defaultMethod);setMode('single')}},[open,total,defaultMethod])
  const maxBonus=customer&&state.settings.pos.bonusEnabled?Math.min(customer.bonusBalance,total*(state.settings.pos.bonusMaxPercent||0)/100):0
  const payable=Math.max(0,total-(+bonusUsed||0))
  const normalized=mode==='single'?[{method:single,amount:payable,received:single==='Naqd'?+received||0:payable}]:lines.map(x=>({...x,amount:+x.amount||0,received:x.method==='Naqd'?(+x.received||+x.amount||0):(+x.amount||0)}))
  const allocated=normalized.reduce((a,x)=>a+(+x.amount||0),0),change=single==='Naqd'&&mode==='single'?Math.max(0,(+received||0)-payable):0
  const cashValid=mode==='single'?(single!=='Naqd'||(+received||0)>=payable):normalized.every(x=>x.method!=='Naqd'||(+x.received||0)>=(+x.amount||0))
  const valid=Math.abs(allocated-payable)<1&&cashValid&&methods.length>0
  const update=(i,key,val)=>setLines(ls=>ls.map((x,idx)=>idx===i?{...x,[key]:key==='amount'?+val||0:val}:x))
  const icon=m=>m==='Naqd'?<Banknote/>:m==='Karta'?<CreditCard/>:m==='QR'?<QrCode/>:m==='Nasiya'?<ReceiptText/>:<WalletCards/>
  return <Modal open={open} onClose={onClose} title="To‘lovni yakunlash" eyebrow="TO‘LOV" subtitle={`Jami: ${Number(total).toLocaleString('uz-UZ')} so‘m`} size="lg" footer={<><button className="secondary-glass-btn" onClick={onClose}>Bekor</button><button className="primary-glass-btn" disabled={!valid} onClick={()=>onDone({payments:normalized,bonusUsed:+bonusUsed||0})}><Check/> Savdoni yakunlash</button></>}>
    {state.settings.pos.splitPayment&&<Segmented items={[{value:'single',label:'Bitta to‘lov'},{value:'split',label:'Aralash to‘lov'}]} value={mode} onChange={setMode}/>} 
    {customer&&maxBonus>0&&<div className="bonus-pay"><div><Gift/><span><b>Bonus balansi: <Money value={customer.bonusBalance}/></b><small>Chekning maksimum {state.settings.pos.bonusMaxPercent}% qismigacha ishlatish mumkin.</small></span></div><Input type="number" min="0" max={maxBonus} value={bonusUsed} onChange={v=>setBonusUsed(Math.min(+v||0,maxBonus))}/></div>}
    {mode==='single'?<><div className="payment-method-grid">{methods.map(m=><button key={m} className={single===m?'active':''} onClick={()=>setSingle(m)}>{icon(m)}<b>{m}</b><span><Money value={payable}/></span></button>)}</div>{single==='Naqd'&&<div className="cash-received"><Field label="Qabul qilindi" error={!cashValid?'Qabul qilingan summa yetarli emas.':''}><Input type="number" value={received} min={payable} onChange={setReceived}/></Field><div><span>Qaytim</span><b><Money value={change}/></b></div></div>}</>:<div className="split-lines">{lines.map((l,i)=>{const cash=l.method==='Naqd';const cashReceived=+l.received||+l.amount||0;const lineChange=cash?Math.max(0,cashReceived-(+l.amount||0)):0;return <div className={`split-line ${cash?'cash-line':''}`} key={i}><Select value={l.method} onChange={v=>update(i,'method',v)}>{methods.map(m=><option key={m}>{m}</option>)}</Select><Input type="number" min="0" value={l.amount} onChange={v=>update(i,'amount',v)}/>{cash&&<Input type="number" min={l.amount||0} value={l.received??l.amount} onChange={v=>update(i,'received',v)} placeholder="Qabul qilindi"/>}{cash&&<span className="split-change">Qaytim: <b><Money value={lineChange}/></b></span>}{lines.length>1&&<button className="icon-ghost" onClick={()=>setLines(ls=>ls.filter((_,idx)=>idx!==i))}><Trash2/></button>}</div>})}<button className="soft-glass-btn" onClick={()=>setLines(ls=>[...ls,{method:methods.find(x=>x!=='Naqd')||defaultMethod,amount:Math.max(0,payable-ls.reduce((a,x)=>a+(+x.amount||0),0))}])}><Plus/> To‘lov qatori</button><p className={valid?'split-ok':'split-warn'}>Ajratildi: <Money value={allocated}/> / <Money value={payable}/></p></div>}
  </Modal>
}
