import React,{useMemo,useState} from 'react'
import {useSearchParams} from 'react-router-dom'
import {BarChart3,Boxes,ShoppingCart,Users,WalletCards,Download,Warehouse,Truck,Scale,TrendingUp,Search,Sparkles} from 'lucide-react'
import {PageHeader,Card,KPI,Money,Segmented,Status} from '../components/UI'
import {useApp} from '../state/AppContext'

const configs={
  overview:{title:'Umumiy hisobot',subtitle:'Biznesning asosiy ko‘rsatkichlari va umumiy holati.',icon:BarChart3},
  sales:{title:'Savdo hisoboti',subtitle:'Savdo, cheklar, to‘lovlar va davr dinamikasi.',icon:TrendingUp},
  products:{title:'Mahsulotlar hisoboti',subtitle:'Sotuv, foyda, marja va stock aging tahlili.',icon:Boxes},
  warehouse:{title:'Ombor hisoboti',subtitle:'Qoldiq, qiymat, aylanish va stock risklari.',icon:Warehouse},
  purchases:{title:'Xaridlar hisoboti',subtitle:'Supplier, narxlar va qabul holati.',icon:ShoppingCart},
  customers:{title:'Mijozlar hisoboti',subtitle:'Faollik, qarz, bonus va retention ko‘rsatkichlari.',icon:Users},
  finance:{title:'Moliya hisoboti',subtitle:'Kirim-chiqim, foyda, cash flow va xarajatlar.',icon:WalletCards},
  debts:{title:'Qarzdorlik hisoboti',subtitle:'Debitor va kreditor qarzlar, aging va due date.',icon:Scale},
}

export default function Reports(){
  const {state}=useApp(),[p]=useSearchParams(),view=p.get('view')||'overview';const [period,setPeriod]=useState('Oy');const cfg=configs[view]||configs.overview
  const exportCsv=()=>{const rows=buildExport(view,state);const keys=Object.keys(rows[0]||{Natija:'Ma’lumot yo‘q'});const csv=[keys.join(','),...rows.map(r=>keys.map(k=>String(r[k]??'').replaceAll(',',' ')).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`zenix-report-${view}.csv`;a.click();URL.revokeObjectURL(a.href)}
  return <><PageHeader title={cfg.title} subtitle={cfg.subtitle} actions={<><Segmented items={['Bugun','Hafta','Oy','Chorak','Yil']} value={period} onChange={setPeriod}/><button className="soft-glass-btn" onClick={exportCsv}><Download/> Export</button></>}/>{view==='overview'&&<Overview state={state}/>} {view==='sales'&&<SalesReport state={state}/>} {view==='products'&&<ProductsReport state={state}/>} {view==='warehouse'&&<WarehouseReport state={state}/>} {view==='purchases'&&<PurchasesReport state={state}/>} {view==='customers'&&<CustomersReport state={state}/>} {view==='finance'&&<FinanceReport state={state}/>} {view==='debts'&&<DebtsReport state={state}/>}</>}

function Overview({state}){const revenue=state.sales.reduce((a,x)=>a+x.amount,0),cogs=calcCogs(state),expense=state.financeTransactions.filter(x=>x.type==='Chiqim').reduce((a,x)=>a+x.amount,0),gross=revenue-cogs,net=gross-expense,stock=state.products.reduce((a,p)=>a+p.cost*p.stock,0),customerDebt=state.customers.reduce((a,c)=>a+c.debt,0),supplierDebt=state.supplierDebts.reduce((a,d)=>a+d.amount-d.paid,0);return <><div className="report-kpis"><KPI label="Jami savdo" value={<Money value={revenue}/>} delta="+12%" icon={<TrendingUp/>}/><KPI label="Yalpi foyda" value={<Money value={gross}/>} delta="+18%" icon={<BarChart3/>}/><KPI label="Sof foyda" value={<Money value={net}/>} delta="+9%" icon={<WalletCards/>}/><KPI label="Ombor qiymati" value={<Money value={stock}/>} icon={<Boxes/>}/><KPI label="Mijozlar qarzi" value={<Money value={customerDebt}/>} icon={<Users/>}/><KPI label="Supplier qarzi" value={<Money value={supplierDebt}/>} icon={<Truck/>}/></div><div className="reports-overview-grid"><Card className="simple-chart-card"><div className="card-title"><b>Savdo va foyda dinamikasi</b><span>Sodda ko‘rinish</span></div><SimpleChart values={[42,51,47,58,63,69,76,72,85]} line={[22,28,25,34,38,41,46,44,53]}/></Card><Card><div className="card-title"><b>Davr taqqoslash</b><span>Oldingi oy</span></div><div className="compare-list"><p><span>Savdo</span><b><Money value={revenue}/></b><em>+12%</em></p><p><span>Sof foyda</span><b><Money value={net}/></b><em>+9%</em></p><p><span>Cheklar</span><b>{state.sales.length} ta</b><em>+6%</em></p><p><span>O‘rtacha chek</span><b><Money value={state.sales.length?revenue/state.sales.length:0}/></b><em>+5%</em></p></div></Card></div><div className="three-panel-grid"><TopProducts state={state}/><TopCustomers state={state}/><Card><div className="card-title"><b>AI tahlil</b><Sparkles/></div><div className="ai-summary-box"><p>Savdo ijobiy, lekin kam qoldiq va supplier qarzlari biznes egasi e’tiborini talab qiladi.</p><ul><li>{state.products.filter(p=>p.stock<=p.minStock).length} ta mahsulot kam qolgan</li><li>{state.customers.filter(c=>c.debt>0).length} ta qarzdor mijoz</li><li>{state.purchases.filter(p=>p.receiptStatus!=='Qabul qilindi').length} ta kutilayotgan xarid</li></ul></div></Card></div></>}
function SalesReport({state}){const revenue=state.sales.reduce((a,x)=>a+x.amount,0),avg=state.sales.length?revenue/state.sales.length:0,returns=state.salesReturns.reduce((a,r)=>a+r.amount,0),discount=state.sales.reduce((a,s)=>a+(s.discount||0),0),credit=state.sales.flatMap(s=>s.payments).filter(p=>p.method==='Nasiya').reduce((a,p)=>a+p.amount,0);return <><div className="kpi-grid"><KPI label="Savdo summasi" value={<Money value={revenue}/>} icon={<TrendingUp/>}/><KPI label="Cheklar" value={`${state.sales.length} ta`} icon={<BarChart3/>}/><KPI label="O‘rtacha chek" value={<Money value={avg}/>} icon={<WalletCards/>}/><KPI label="Qaytarish" value={<Money value={returns}/>} icon={<Scale/>}/><KPI label="Chegirma" value={<Money value={discount}/>} icon={<Scale/>}/><KPI label="Nasiya" value={<Money value={credit}/>} icon={<WalletCards/>}/></div><Card><div className="card-title"><b>Kunlik savdo dinamikasi</b><span>1 ta asosiy grafik</span></div><SimpleChart values={[30,45,38,62,52,71,68,80,77,89]}/></Card><Card><table><thead><tr><th>Sale #</th><th>Sana</th><th>Mijoz</th><th>Kassir</th><th>To‘lov</th><th>Summa</th><th>Status</th></tr></thead><tbody>{state.sales.map(s=><tr key={s.id}><td>{s.id}</td><td>{s.date} {s.time}</td><td>{s.customer}</td><td>{s.cashier}</td><td>{s.payment}</td><td><Money value={s.amount}/></td><td><Status>{s.status}</Status></td></tr>)}</tbody></table></Card></>}
function ProductsReport({state}){const cogs=calcCogs(state),revenue=state.sales.reduce((a,s)=>a+s.items.reduce((b,i)=>b+i.qty*i.price,0),0),margin=revenue?Math.round((revenue-cogs)/revenue*1000)/10:0;return <><div className="kpi-grid"><KPI label="Sotilgan qty" value={`${state.sales.flatMap(s=>s.items).reduce((a,i)=>a+i.qty,0)} ta`} icon={<Boxes/>}/><KPI label="Revenue" value={<Money value={revenue}/>} icon={<TrendingUp/>}/><KPI label="COGS" value={<Money value={cogs}/>} icon={<WalletCards/>}/><KPI label="Marja" value={`${margin}%`} icon={<Scale/>}/><KPI label="Dead stock" value={`${state.products.filter(p=>p.stock>0&&!state.sales.some(s=>s.items.some(i=>i.productId===p.id))).length} ta`} icon={<Boxes/>}/></div><Card><div className="card-title"><b>Mahsulot profitability</b><span>Revenue · COGS · Marja</span></div><table><thead><tr><th>Mahsulot</th><th>Sotilgan</th><th>Revenue</th><th>COGS</th><th>Gross profit</th><th>Margin</th><th>Qoldiq</th></tr></thead><tbody>{state.products.map(p=>{const qty=state.sales.flatMap(s=>s.items).filter(i=>i.productId===p.id).reduce((a,i)=>a+i.qty,0),rev=state.sales.flatMap(s=>s.items).filter(i=>i.productId===p.id).reduce((a,i)=>a+i.qty*i.price,0),cg=qty*p.cost,g=rev-cg,m=rev?Math.round(g/rev*1000)/10:0;return <tr key={p.id}><td>{p.name}</td><td>{qty}</td><td><Money value={rev}/></td><td><Money value={cg}/></td><td><Money value={g}/></td><td>{m}%</td><td><Status>{p.stock<=p.minStock?'Kam':p.stock}</Status></td></tr>})}</tbody></table></Card></>}
function WarehouseReport({state}){const stock=state.products.reduce((a,p)=>a+p.stock,0),value=state.products.reduce((a,p)=>a+p.stock*p.cost,0),reserved=state.products.reduce((a,p)=>a+(p.reserved||0),0),low=state.products.filter(p=>p.stock<=p.minStock).length,expiry=state.products.filter(p=>p.trackExpiry).length;return <><div className="kpi-grid"><KPI label="Jami stock" value={`${stock} birlik`} icon={<Boxes/>}/><KPI label="Stock value" value={<Money value={value}/>} icon={<WalletCards/>}/><KPI label="Band qilingan" value={`${reserved} birlik`} icon={<Warehouse/>}/><KPI label="Kam / tugagan" value={`${low} ta`} icon={<Scale/>}/><KPI label="Srok nazorati" value={`${expiry} ta`} icon={<Boxes/>}/></div><Card><table><thead><tr><th>Mahsulot</th><th>Qoldiq</th><th>Band</th><th>Sotish mumkin</th><th>Qiymat</th><th>Min</th><th>Status</th></tr></thead><tbody>{state.products.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.stock}</td><td>{p.reserved||0}</td><td>{Math.max(0,p.stock-(p.reserved||0))}</td><td><Money value={p.stock*p.cost}/></td><td>{p.minStock}</td><td><Status>{p.stock===0?'Tugagan':p.stock<=p.minStock?'Kam':'Yetarli'}</Status></td></tr>)}</tbody></table></Card></>}
function PurchasesReport({state}){const total=state.purchases.reduce((a,p)=>a+p.amount,0),received=state.purchases.filter(p=>p.receiptStatus==='Qabul qilindi').length,pending=state.purchases.length-received,returns=state.supplierReturns.reduce((a,r)=>a+r.amount,0);return <><div className="kpi-grid"><KPI label="Jami xarid" value={<Money value={total}/>} icon={<ShoppingCart/>}/><KPI label="Qabul qilingan" value={`${received} ta`} icon={<Boxes/>}/><KPI label="Kutilayotgan" value={`${pending} ta`} icon={<Truck/>}/><KPI label="Supplier return" value={<Money value={returns}/>} icon={<Scale/>}/></div><Card><table><thead><tr><th>PO</th><th>Supplier</th><th>Sana</th><th>Item</th><th>Summa</th><th>Qabul</th><th>To‘lov</th></tr></thead><tbody>{state.purchases.map(p=><tr key={p.id}><td>{p.id}</td><td>{p.supplier}</td><td>{p.date}</td><td>{p.items.length}</td><td><Money value={p.amount}/></td><td><Status>{p.receiptStatus}</Status></td><td><Status>{p.paymentStatus}</Status></td></tr>)}</tbody></table></Card></>}
function CustomersReport({state}){const total=state.customers.length,active=state.customers.filter(c=>c.status==='Faol').length,debt=state.customers.reduce((a,c)=>a+c.debt,0),bonus=state.customers.reduce((a,c)=>a+c.bonusBalance,0),avg=total?state.customers.reduce((a,c)=>a+c.total,0)/total:0;return <><div className="kpi-grid"><KPI label="Jami mijoz" value={total} icon={<Users/>}/><KPI label="Faol" value={active} icon={<Users/>}/><KPI label="O‘rtacha xarid" value={<Money value={avg}/>} icon={<WalletCards/>}/><KPI label="Jami qarz" value={<Money value={debt}/>} icon={<Scale/>}/><KPI label="Bonus balans" value={<Money value={bonus}/>} icon={<WalletCards/>}/></div><Card><table><thead><tr><th>Mijoz</th><th>Guruh</th><th>Jami xarid</th><th>Qarz</th><th>Bonus</th><th>Oxirgi xarid</th><th>Status</th></tr></thead><tbody>{state.customers.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.group}</td><td><Money value={c.total}/></td><td><Money value={c.debt}/></td><td><Money value={c.bonusBalance}/></td><td>{c.lastPurchase||'—'}</td><td><Status>{c.status}</Status></td></tr>)}</tbody></table></Card></>}
function FinanceReport({state}){const income=state.financeTransactions.filter(x=>x.type==='Kirim').reduce((a,x)=>a+x.amount,0),expense=state.financeTransactions.filter(x=>x.type==='Chiqim').reduce((a,x)=>a+x.amount,0),cogs=calcCogs(state),revenue=state.sales.reduce((a,x)=>a+x.amount,0),net=revenue-cogs-expense;return <><div className="kpi-grid"><KPI label="Kirim" value={<Money value={income}/>} icon={<TrendingUp/>}/><KPI label="Chiqim" value={<Money value={expense}/>} icon={<Scale/>}/><KPI label="Net cash" value={<Money value={income-expense}/>} icon={<WalletCards/>}/><KPI label="Revenue" value={<Money value={revenue}/>} icon={<TrendingUp/>}/><KPI label="Net profit" value={<Money value={net}/>} icon={<BarChart3/>}/></div><Card><div className="card-title"><b>Moliyaviy harakatlar</b></div><table><thead><tr><th>Sana</th><th>Turi</th><th>Kategoriya</th><th>Hisob</th><th>Summa</th><th>Status</th></tr></thead><tbody>{state.financeTransactions.map(x=><tr key={x.id}><td>{x.date}</td><td>{x.type}</td><td>{x.category}</td><td>{x.account}</td><td><Money value={x.amount}/></td><td><Status>{x.status}</Status></td></tr>)}</tbody></table></Card></>}
function DebtsReport({state}){const c=state.customerDebts.reduce((a,d)=>a+Math.max(0,d.amount-d.paid),0),s=state.supplierDebts.reduce((a,d)=>a+Math.max(0,d.amount-d.paid),0);return <><div className="kpi-grid"><KPI label="Debitor" value={<Money value={c}/>} icon={<Users/>}/><KPI label="Kreditor" value={<Money value={s}/>} icon={<Truck/>}/><KPI label="Net debt" value={<Money value={c-s}/>} icon={<Scale/>}/></div><div className="two-panel-grid"><Card><div className="card-title"><b>Mijozlar qarzi</b></div>{state.customerDebts.map(d=><div className="line-summary" key={d.id}><span><b>{state.customers.find(c=>c.id===d.customerId)?.name}</b><small>{d.source} · Due {d.dueDate||'—'}</small></span><b><Money value={d.amount-d.paid}/></b></div>)}</Card><Card><div className="card-title"><b>Supplier qarzi</b></div>{state.supplierDebts.map(d=><div className="line-summary" key={d.id}><span><b>{state.suppliers.find(s=>s.id===d.supplierId)?.name}</b><small>{d.source} · Due {d.dueDate||'—'}</small></span><b><Money value={d.amount-d.paid}/></b></div>)}</Card></div><Card><div className="card-title"><b>Aging</b><span>0–7 / 8–30 / 31–60 / 61–90 / 90+</span></div><div className="aging-grid">{['0–7 kun','8–30 kun','31–60 kun','61–90 kun','90+ kun'].map((x,i)=><div key={x}><span>{x}</span><b><Money value={[c*.35,c*.28,c*.18,c*.12,c*.07][i]}/></b></div>)}</div></Card></>}
function TopProducts({state}){return <Card><div className="card-title"><b>Eng ko‘p sotilgan mahsulotlar</b><span>Top 5</span></div><div className="rank-list compact">{state.products.slice(0,5).map((p,i)=><div key={p.id}><strong>{i+1}</strong><span>{p.name}</span><b>{p.stock} {p.unit}</b><Money value={p.price*p.stock}/></div>)}</div></Card>}
function TopCustomers({state}){return <Card><div className="card-title"><b>Eng yaxshi mijozlar</b><span>Top 5</span></div><div className="rank-list compact">{[...state.customers].sort((a,b)=>b.total-a.total).slice(0,5).map((c,i)=><div key={c.id}><strong>{i+1}</strong><span>{c.name}</span><b><Money value={c.total}/></b><span>{c.group}</span></div>)}</div></Card>}
function SimpleChart({values,line}){return <div className="simple-chart"><div className="simple-bars">{values.map((v,i)=><div key={i}><i style={{height:`${v}%`}}/><span>{i+1}</span></div>)}</div>{line&&<svg viewBox="0 0 100 60" preserveAspectRatio="none" className="simple-line"><polyline fill="none" points={line.map((v,i)=>`${i/(line.length-1)*100},${60-v*.55}`).join(' ')}/></svg>}</div>}
function calcCogs(state){let c=0;state.sales.forEach(s=>s.items.forEach(i=>{c+=(state.products.find(p=>p.id===i.productId)?.cost||0)*i.qty}));return c}
function buildExport(view,state){if(view==='sales')return state.sales.map(s=>({Sale:s.id,Sana:s.date,Mijoz:s.customer,Summa:s.amount,ToLov:s.payment}));if(view==='products')return state.products.map(p=>({Mahsulot:p.name,SKU:p.sku,Qoldiq:p.stock,Tannarx:p.cost,Narx:p.price}));if(view==='warehouse')return state.products.map(p=>({Mahsulot:p.name,Qoldiq:p.stock,Band:p.reserved||0,Qiymat:p.stock*p.cost}));if(view==='purchases')return state.purchases.map(p=>({PO:p.id,Supplier:p.supplier,Sana:p.date,Summa:p.amount,Qabul:p.receiptStatus}));if(view==='customers')return state.customers.map(c=>({Mijoz:c.name,Guruh:c.group,Jami:c.total,Qarz:c.debt,Bonus:c.bonusBalance}));if(view==='finance')return state.financeTransactions.map(x=>({Sana:x.date,Turi:x.type,Kategoriya:x.category,Summa:x.amount,Hisob:x.account}));if(view==='debts')return [...state.customerDebts.map(d=>({Tur:'Debitor',Nomi:state.customers.find(c=>c.id===d.customerId)?.name,Qoldiq:d.amount-d.paid,Due:d.dueDate})),...state.supplierDebts.map(d=>({Tur:'Kreditor',Nomi:state.suppliers.find(s=>s.id===d.supplierId)?.name,Qoldiq:d.amount-d.paid,Due:d.dueDate}))];return [{Savdo:state.sales.reduce((a,x)=>a+x.amount,0),Mijozlar:state.customers.length,Mahsulotlar:state.products.length}]}
