import React,{useMemo,useState} from 'react'
import {useNavigate,useSearchParams} from 'react-router-dom'
import {Plus,ShoppingBag,ReceiptText,WalletCards,RotateCcw,ArrowRight,Search,Filter,X,Printer,Undo2,AlertCircle,Crown,Clock3,CashRegister,DoorOpen,DoorClosed} from 'lucide-react'
import {PageHeader,Card,KPI,Money,Status,Modal,Drawer,Field,Input,Select,Toast} from '../components/UI'
import {useApp} from '../state/AppContext'

export default function Sales(){
  const {state,createReturn,openShift,closeShift}=useApp(),[params,setParams]=useSearchParams(),nav=useNavigate();const view=params.get('view')||'overview'
  const [detail,setDetail]=useState(null),[returnSale,setReturnSale]=useState(null),[toast,setToast]=useState('')
  const todayTotal=state.sales.reduce((a,x)=>a+x.amount,0),checks=state.sales.length,avg=checks?Math.round(todayTotal/checks):0,returned=state.salesReturns.reduce((a,x)=>a+x.amount,0),credit=state.sales.reduce((a,x)=>a+x.payments.filter(p=>p.method==='Nasiya').reduce((b,p)=>b+p.amount,0),0)
  const payments=['Naqd','Karta','QR','Nasiya']
  return <>
    <PageHeader title="Savdo" subtitle="Bugungi savdo holati, tarix, qaytarish va nasiya nazorati." actions={<button className="primary-glass-btn" onClick={()=>nav('/pos')}><Plus/> Yangi savdo</button>}/>
    {view==='overview'&&<><div className="sales-overview-kpis"><KPI label="Bugungi savdo" value={<Money value={todayTotal}/>} delta="+18.5%" icon={<ShoppingBag/>}/><KPI label="Cheklar" value={`${checks} ta`} delta="+8.1%" icon={<ReceiptText/>}/><KPI label="O‘rtacha chek" value={<Money value={avg}/>} delta="+4.7%" icon={<WalletCards/>}/><KPI label="Qaytarishlar" value={<Money value={returned}/>} delta="-1.2%" icon={<RotateCcw/>}/><KPI label="Nasiya" value={<Money value={credit}/>} icon={<WalletCards/>}/></div><div className="sales-control-grid"><Card className="sales-compact-cta"><div><span className="eyebrow">TEZKOR KASSA</span><h2>Yangi savdo</h2><p>Barcode, bonus, split payment, nasiya va saqlangan savat bilan.</p></div><button className="primary-glass-btn" onClick={()=>nav('/pos')}>POS / Kassa ochish <ArrowRight/></button><div className="cta-orb"><ShoppingBag/></div></Card><Card><div className="card-title"><b>To‘lovlar bo‘yicha</b><span>Bugun</span></div><div className="payment-stats compact">{payments.map((p,i)=>{const sum=state.sales.flatMap(x=>x.payments||[]).filter(x=>x.method===p).reduce((a,x)=>a+x.amount,0),pct=todayTotal?Math.round(sum/todayTotal*100):0;return <div key={p}><span><i className={`pay-dot p${i}`}/>{p}<small>{pct}%</small></span><b><Money value={sum}/></b></div>})}</div></Card><Card><div className="card-title"><b>Bugungi holat</b><span>Operatsion insight</span></div><div className="insight-list"><div><span className="insight-icon warn"><AlertCircle/></span><span><b>{state.customerDebts.filter(d=>d.status!=='To‘langan').length} ta faol qarz</b><small>Due date va to‘lovlarni kuzating</small></span></div><div><span className="insight-icon violet"><Crown/></span><span><b>Eng faol kassir: Sardor</b><small>8 200 000 so‘m savdo</small></span></div><div><span className="insight-icon blue"><Clock3/></span><span><b>Peak hour: 13:00–15:00</b><small>Bugungi savdoning 34%</small></span></div></div></Card></div><Card><div className="card-title"><b>So‘nggi sotuvlar</b><button className="link-btn" onClick={()=>setParams({view:'history'})}>Barchasi →</button></div><SalesTable rows={state.sales} onOpen={setDetail}/></Card></>}
    {view==='history'&&<SalesHistory rows={state.sales} onOpen={setDetail}/>} 
    {view==='returns'&&<Returns rows={state.salesReturns} onNew={()=>setReturnSale({})}/>} 
    {view==='credit'&&<CreditSales state={state} onOpen={setDetail}/>} 
    {view==='registers'&&<RegisterShifts state={state} openShift={openShift} closeShift={closeShift} toast={m=>setToast(m)}/>} 
    {detail&&<SaleDetail sale={detail} onClose={()=>setDetail(null)} onReturn={()=>setReturnSale(detail)}/>} 
    {returnSale&&<ReturnModal state={state} sale={returnSale} onClose={()=>setReturnSale(null)} onSave={(saleId,reason,items)=>{createReturn({saleId,reason,items});setReturnSale(null);setToast('Qaytarish yakunlandi: stock, bonus, qarz va moliya yangilandi.')}}/>}
    <Toast message={toast} onDone={()=>setToast('')}/>
  </>
}

function SalesHistory({rows,onOpen}){const [q,setQ]=useState(''),[method,setMethod]=useState('Barchasi');const data=rows.filter(x=>(x.id+' '+x.customer).toLowerCase().includes(q.toLowerCase())&&(method==='Barchasi'||x.payment.includes(method)));return <Card><div className="toolbar"><div className="mini-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Chek raqami, mijoz yoki summa..."/></div><Select className="history-method-select" value={method} onChange={setMethod}><option>Barchasi</option><option>Naqd</option><option>Karta</option><option>QR</option><option>Nasiya</option></Select><button className="soft-glass-btn compact" onClick={()=>{setQ('');setMethod('Barchasi')}}><Filter/> Filtrlarni tozalash</button></div><SalesTable rows={data} onOpen={onOpen}/></Card>}
function SalesTable({rows,onOpen}){return <div className="responsive-table"><table><thead><tr><th>#</th><th>Sana / vaqt</th><th>Mijoz</th><th>Mahsulot</th><th>To‘lov</th><th>Summa</th><th>Status</th></tr></thead><tbody>{rows.map(s=><tr key={s.id} className="click-row" onClick={()=>onOpen?.(s)}><td><b>{s.id}</b></td><td>{s.date} · {s.time}</td><td>{s.customer}</td><td>{s.items.reduce((a,x)=>a+x.qty,0)} ta</td><td>{s.payment}</td><td><b><Money value={s.amount}/></b></td><td><Status>{s.status}</Status></td></tr>)}</tbody></table></div>}
function Returns({rows,onNew}){return <Card><div className="card-title"><b>Qaytarishlar</b><button className="primary-glass-btn compact" onClick={onNew}><Plus/> Qaytarish yaratish</button></div><table><thead><tr><th>#</th><th>Savdo</th><th>Mijoz</th><th>Sabab</th><th>Summa</th><th>Sana</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.id}</td><td>{r.saleId}</td><td>{r.customer}</td><td>{r.reason}</td><td><Money value={r.amount}/></td><td>{r.date} {r.time}</td><td><Status>{r.status}</Status></td></tr>)}</tbody></table></Card>}
function CreditSales({state,onOpen}){const debtSales=state.sales.filter(s=>s.payments.some(p=>p.method==='Nasiya'));return <Card><div className="card-title"><b>Nasiya savdolar</b><span>{debtSales.length} ta</span></div><table><thead><tr><th>#</th><th>Mijoz</th><th>Nasiya summa</th><th>Sana</th><th>Holat</th></tr></thead><tbody>{debtSales.map(s=><tr className="click-row" key={s.id} onClick={()=>onOpen(s)}><td>{s.id}</td><td>{s.customer}</td><td><Money value={s.payments.filter(p=>p.method==='Nasiya').reduce((a,p)=>a+p.amount,0)}/></td><td>{s.date}</td><td><Status>Nasiya</Status></td></tr>)}</tbody></table></Card>}
function RegisterShifts({state,openShift,closeShift,toast}){const [open,setOpen]=useState(false),[close,setClose]=useState(null);return <><div className="kpi-grid"><KPI label="Kassalar" value={`${state.registers.length} ta`} icon={<CashRegister/>}/><KPI label="Ochiq smena" value={`${state.shifts.filter(x=>x.status==='Ochiq').length} ta`} icon={<DoorOpen/>}/><KPI label="Yopilgan" value={`${state.shifts.filter(x=>x.status==='Yopilgan').length} ta`} icon={<DoorClosed/>}/></div><Card><div className="card-title"><b>Kassalar va smenalar</b><button className="primary-glass-btn compact" onClick={()=>setOpen(true)}><DoorOpen/> Smena ochish</button></div><table><thead><tr><th>Kassa</th><th>Xodim</th><th>Ochildi</th><th>Opening cash</th><th>Expected</th><th>Status</th><th/></tr></thead><tbody>{state.registers.map(r=>{const sh=state.shifts.find(x=>x.registerId===r.id&&x.status==='Ochiq');return <tr key={r.id}><td><b>{r.name}</b></td><td>{sh?.employee||'—'}</td><td>{sh?.openedAt||'—'}</td><td><Money value={sh?.openingCash||0}/></td><td><Money value={sh?.expectedCash||0}/></td><td><Status>{sh?'Ochiq':'Yopiq'}</Status></td><td>{sh&&<button className="soft-glass-btn compact" onClick={()=>setClose(sh)}>Smena yopish</button>}</td></tr>})}</tbody></table></Card><ShiftOpen open={open} onClose={()=>setOpen(false)} state={state} onSave={v=>{openShift(v);setOpen(false);toast('Smena ochildi.')}}/><ShiftClose shift={close} onClose={()=>setClose(null)} onSave={v=>{closeShift({...v,shiftId:close.id});setClose(null);toast('Smena yopildi.')}}/></>}
function ShiftOpen({open,onClose,state,onSave}){const [employeeId,setEmployee]=useState(state.employees[0]?.id||''),[registerId,setRegister]=useState(state.registers[0]?.id||''),[cash,setCash]=useState(0);return <Modal open={open} onClose={onClose} title="Smena ochish" eyebrow="KASSA" footer={<><button className="secondary-glass-btn" onClick={onClose}>Bekor</button><button className="primary-glass-btn" onClick={()=>onSave({employeeId,registerId,openingCash:cash})}>Ochish</button></>}><Field label="Xodim"><Select value={employeeId} onChange={setEmployee}>{state.employees.filter(e=>e.status==='Faol').map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</Select></Field><Field label="Kassa"><Select value={registerId} onChange={setRegister}>{state.registers.filter(r=>r.status==='Faol').map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</Select></Field><Field label="Boshlang‘ich naqd"><Input type="number" min="0" value={cash} onChange={setCash}/></Field></Modal>}
function ShiftClose({shift,onClose,onSave}){const [cash,setCash]=useState(''),[reason,setReason]=useState('');return <Modal open={!!shift} onClose={onClose} title="Smena yopish" eyebrow="KASSA" subtitle={`Expected: ${Number(shift?.expectedCash||0).toLocaleString('uz-UZ')} so‘m`} footer={<><button className="secondary-glass-btn" onClick={onClose}>Bekor</button><button className="primary-glass-btn" onClick={()=>onSave({actualCash:cash,reason})}>Yopish</button></>}><Field label="Real sanalgan naqd"><Input type="number" min="0" value={cash} onChange={setCash}/></Field><Field label="Izoh / sabab" hint="Kassa farqi yoki smena erta yopilsa sabab majburiy."><Input value={reason} onChange={setReason} placeholder="Sabab yozing"/></Field></Modal>}
function SaleDetail({sale,onClose,onReturn}){return <Drawer onClose={onClose} title={sale.id} eyebrow="SAVDO DETALI" subtitle={`${sale.date} · ${sale.time}`} actions={<><button className="secondary-glass-btn" onClick={()=>printReceipt(sale)}><Printer/> Chek chiqarish</button><button className="danger-glass-btn" onClick={onReturn}><Undo2/> Qaytarish</button></>}><div className="detail-grid"><div><span>Mijoz</span><b>{sale.customer}</b></div><div><span>Kassir</span><b>{sale.cashier}</b></div><div><span>Kassa</span><b>{sale.registerId}</b></div><div><span>To‘lov</span><b>{sale.payment}</b></div></div><div className="detail-section"><h3>Mahsulotlar</h3>{sale.items.map(i=><div className="line-summary" key={i.productId}><span><b>{i.name}</b><small>{i.qty} × {Number(i.price).toLocaleString('uz-UZ')}</small></span><strong><Money value={i.qty*i.price}/></strong></div>)}</div><div className="detail-section"><h3>To‘lovlar</h3>{sale.payments.map((p,i)=><div className="line-summary" key={i}><span>{p.method}</span><b><Money value={p.amount}/></b></div>)}</div><div className="receipt-summary"><p><span>Chegirma</span><b><Money value={sale.discount}/></b></p><p><span>Jami</span><b><Money value={sale.amount}/></b></p></div></Drawer>}
function printReceipt(sale){
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))
  const items=(sale.items||[]).map(i=>`<tr><td>${esc(i.name)}</td><td>${esc(i.qty)} × ${Number(i.price||0).toLocaleString('uz-UZ')}</td><td>${Number((i.qty||0)*(i.price||0)).toLocaleString('uz-UZ')}</td></tr>`).join('')
  const payments=(sale.payments||[]).map(p=>`<div class="row"><span>${esc(p.method)}</span><b>${Number(p.amount||0).toLocaleString('uz-UZ')} so‘m</b></div>`).join('')
  const w=window.open('','_blank','width=420,height=720')
  if(!w)return
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(sale.id)} — Chek</title><style>@page{size:80mm auto;margin:0}*{box-sizing:border-box}body{font-family:Arial,sans-serif;width:80mm;margin:0;padding:5mm;color:#111;font-size:11px}.head{text-align:center;margin-bottom:4mm}.head h2{margin:0 0 2mm}.meta,.row{display:flex;justify-content:space-between;gap:8px;margin:1.4mm 0}.line{border-top:1px dashed #777;margin:3mm 0}table{width:100%;border-collapse:collapse}td{padding:1.7mm 0;border-bottom:1px dotted #bbb}td:nth-child(2){text-align:center}td:last-child{text-align:right;font-weight:700}.total{font-size:15px}.muted{color:#666}.foot{text-align:center;margin-top:4mm;font-size:9px}</style></head><body><div class="head"><h2>ZENIX Savdo</h2><div class="muted">${esc(sale.id)} · ${esc(sale.date)} ${esc(sale.time)}</div></div><div class="meta"><span>Mijoz</span><b>${esc(sale.customer)}</b></div><div class="meta"><span>Kassir</span><b>${esc(sale.cashier)}</b></div><div class="line"></div><table>${items}</table><div class="line"></div>${payments}<div class="row"><span>Chegirma</span><b>${Number(sale.discount||0).toLocaleString('uz-UZ')} so‘m</b></div><div class="row total"><span>JAMI</span><b>${Number(sale.amount||0).toLocaleString('uz-UZ')} so‘m</b></div><div class="foot">Xaridingiz uchun rahmat!</div><script>window.onload=()=>{window.print()}<\/script></body></html>`)
  w.document.close()
}

function saleAgeDays(value){const v=String(value||'');let d=null;if(/^\d{2}\.\d{2}\.\d{4}$/.test(v)){const [dd,mm,yy]=v.split('.').map(Number);d=new Date(yy,mm-1,dd)}else if(/^\d{4}-\d{2}-\d{2}$/.test(v)){const [yy,mm,dd]=v.split('-').map(Number);d=new Date(yy,mm-1,dd)}if(!d||Number.isNaN(d.getTime()))return 0;const n=new Date(),today=new Date(n.getFullYear(),n.getMonth(),n.getDate());return Math.max(0,Math.floor((today-d)/86400000))}
function ReturnModal({state,sale,onClose,onSave}){
  const returnableSales=useMemo(()=>state.sales.filter(s=>{
    const limit=+state.settings?.pos?.returnDays||0;if(limit>0&&saleAgeDays(s.date)>limit)return false
    const returned={};state.salesReturns.filter(r=>r.saleId===s.id&&r.status==='Yakunlandi').flatMap(r=>r.items||[]).forEach(i=>{returned[i.productId]=(returned[i.productId]||0)+(+i.qty||0)})
    return (s.items||[]).some(i=>(+i.qty||0)>(returned[i.productId]||0))
  }),[state.sales,state.salesReturns,state.settings?.pos?.returnDays])
  const initialId=sale?.id&&returnableSales.some(s=>s.id===sale.id)?sale.id:(returnableSales[0]?.id||'')
  const [saleId,setSaleId]=useState(initialId),[reason,setReason]=useState('Mahsulot mos kelmadi'),[qtys,setQtys]=useState({}),[error,setError]=useState('')
  const selected=returnableSales.find(s=>s.id===saleId)
  const returnedByProduct=useMemo(()=>{const out={};state.salesReturns.filter(r=>r.saleId===saleId&&r.status==='Yakunlandi').flatMap(r=>r.items||[]).forEach(i=>{out[i.productId]=(out[i.productId]||0)+(+i.qty||0)});return out},[state.salesReturns,saleId])
  const lines=(selected?.items||[]).map(i=>({...i,remaining:Math.max(0,(+i.qty||0)-(returnedByProduct[i.productId]||0)),returnQty:Math.min(Math.max(0,Number(qtys[i.productId])||0),Math.max(0,(+i.qty||0)-(returnedByProduct[i.productId]||0)))})).filter(i=>i.remaining>0)
  const grossSale=(selected?.items||[]).reduce((a,i)=>a+(+i.price||0)*(+i.qty||0),0)||selected?.amount||1
  const netFactor=selected?Math.min(1,(selected.amount||grossSale)/grossSale):1
  const estimated=Math.round(lines.reduce((a,i)=>a+i.returnQty*(+i.price||0),0)*netFactor)
  const selectedQty=lines.reduce((a,i)=>a+i.returnQty,0)
  const setLineQty=(productId,value,max)=>setQtys(q=>({...q,[productId]:Math.max(0,Math.min(max,Number(value)||0))}))
  const chooseSale=v=>{setSaleId(v);setQtys({});setError('')}
  const submit=()=>{if(!saleId)return setError('Qaytariladigan savdoni tanlang.');const items=lines.filter(i=>i.returnQty>0).map(i=>({productId:i.productId,qty:i.returnQty}));if(!items.length)return setError('Kamida bitta mahsulot miqdorini tanlang.');onSave(saleId,reason,items)}
  return <Modal open onClose={onClose} title="Savdoni qaytarish" eyebrow="RETURN" subtitle={selected?`${selected.id} · ${selected.customer}`:'Qaytarish uchun savdo tanlang'} footer={<><button className="secondary-glass-btn" onClick={onClose}>Bekor</button><button className="danger-glass-btn" disabled={!selected||selectedQty<=0} onClick={submit}><Undo2/> Qaytarishni yakunlash</button></>}>
    {returnableSales.length===0?<div className="empty-state compact"><RotateCcw/><b>Qaytarish mumkin bo‘lgan savdo yo‘q</b><span>Barcha savdolar to‘liq qaytarilgan yoki savdo topilmadi.</span></div>:<>
      <Field label="Savdo / chek" error={error}><Select value={saleId} onChange={chooseSale}>{returnableSales.map(s=><option value={s.id} key={s.id}>{s.id} · {s.customer} · {Number(s.amount||0).toLocaleString('uz-UZ')} so‘m</option>)}</Select></Field>
      <Field label="Sabab"><Select value={reason} onChange={setReason}><option>Mahsulot mos kelmadi</option><option>Brak</option><option>Noto‘g‘ri mahsulot</option><option>Mijoz fikrini o‘zgartirdi</option><option>Boshqa</option></Select></Field>
      <div className="return-items"><div className="return-items-head"><b>Qaytariladigan mahsulotlar</b><span>Sotilgan miqdordan ortiq qaytarib bo‘lmaydi</span></div>{lines.map(i=><div className="return-item-row" key={i.productId}><span className="return-item-name"><b>{i.name}</b><small>{Number(i.price||0).toLocaleString('uz-UZ')} so‘m · qolgan {i.remaining} ta</small></span><div className="return-qty-control"><button type="button" onClick={()=>setLineQty(i.productId,i.returnQty-1,i.remaining)} disabled={i.returnQty<=0}>−</button><Input type="number" min="0" max={i.remaining} value={i.returnQty||''} onChange={v=>{setLineQty(i.productId,v,i.remaining);setError('')}}/><button type="button" onClick={()=>setLineQty(i.productId,i.returnQty+1,i.remaining)} disabled={i.returnQty>=i.remaining}>+</button><button type="button" className="return-all-btn" onClick={()=>setLineQty(i.productId,i.remaining,i.remaining)}>Hammasi</button></div></div>)}</div>
      <div className="return-summary"><span><small>Tanlandi</small><b>{selectedQty} ta</b></span><span><small>Hisoblangan refund</small><b><Money value={estimated}/></b></span><span><small>Qaytarish usuli</small><b>Original to‘lov / qarz</b></span></div>
      <div className="return-note"><AlertCircle/><span>Nasiya bo‘lsa avval qarz kamayadi. Qolgan summa original to‘lov usullariga qaytariladi; bonus va ombor qoldig‘i avtomatik qayta hisoblanadi.</span></div>
    </>}
  </Modal>
}
