import { useEffect, useState } from 'react';
import { Bot, Check, Database, FileText, Sparkles, Zap } from 'lucide-react';
import { subscriptionApi, type Plan, type SubscriptionInfo } from '../../services/api/subscriptionApi';
import { getApiErrorMessage } from '../../services/api/apiClient';
import { useToast } from '../../hooks/useToast';
import { useI18n } from '../../i18n/useI18n';
import '../BusinessHub.scss';

const compact = (value: number, locale: string) => new Intl.NumberFormat(locale).format(value);
const Usage = ({label,used,limit,locale}:{label:string;used:number;limit:number;locale:string}) => <div style={{marginTop:14}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12,color:'#8d8798'}}><span>{label}</span><strong>{compact(Math.round(used),locale)} / {compact(limit,locale)}</strong></div><div style={{height:7,marginTop:7,borderRadius:99,background:'rgba(116,82,212,.12)',overflow:'hidden'}}><span style={{display:'block',height:'100%',width:`${Math.min(100,used/Math.max(1,limit)*100)}%`,background:'linear-gradient(90deg,#825bea,#b250de)',borderRadius:99}}/></div></div>;

const Billing = () => {
  const { t, locale } = useI18n();
  const dateLocale = locale === 'ru' ? 'ru-RU' : 'uz-UZ';
  const [plans,setPlans]=useState<Plan[]>([]); const [mine,setMine]=useState<SubscriptionInfo|null>(null); const {showToast}=useToast();
  useEffect(()=>{void Promise.all([subscriptionApi.plans(),subscriptionApi.mine()]).then(([p,m])=>{setPlans(p);setMine(m)}).catch((error)=>showToast(getApiErrorMessage(error,t('billing.loadError','Tariflarni yuklab bo‘lmadi.')),'error'));},[showToast, t]);
  return <main className="business-page"><header className="business-head"><div><span className="business-head__eyebrow">{t('billing.eyebrow','TARIF VA LIMITLAR')}</span><h1>{t('billing.title','Qulay AI tariflari')}</h1><p>{t('billing.subtitle','AI xabarlar, agent amallari, fayllar va uzoq muddatli xotira limiti.')}</p></div>{mine?.trialActive&&<span className="business-badge"><Sparkles size={13}/> {t('billing.trialActive','PRO sinov')} · {mine.trialEndsAt?new Date(mine.trialEndsAt).toLocaleDateString(dateLocale):''} {t('billing.trialUntil','gacha')}</span>}</header>
  {mine&&<section className="business-split"><article className="business-card"><h2>{t('billing.currentUsage','Joriy foydalanish')}</h2><Usage label={t('billing.aiMessages','AI xabarlari')} locale={dateLocale} {...mine.usage.aiMessages}/><Usage label={t('billing.toolActions','Agent amallari')} locale={dateLocale} {...mine.usage.toolActions}/><Usage label={t('nav.files','Fayllar')} locale={dateLocale} {...mine.usage.files}/><Usage label={t('billing.memory','Xotira')} locale={dateLocale} {...mine.usage.memories}/><Usage label={t('billing.storage','Saqlash (MB)')} locale={dateLocale} {...mine.usage.storageMb}/></article><article className="business-card"><span className="business-card__label"><Zap size={16}/> {t('billing.activePlan','Faol imkoniyat')}</span><strong className="business-card__value">{mine.effectiveTier}</strong><p style={{color:'#8d8798',lineHeight:1.6}}>{t('billing.disclaimer','AI har qanday yozish amalidan oldin sizdan tasdiq so‘raydi. Tarif tugasa ma’lumotlaringiz o‘chmaydi.')}</p></article></section>}
  <section className="business-grid" style={{marginTop:14}}>{plans.map((plan)=><article className="business-card" key={plan.tier} style={mine?.effectiveTier===plan.tier?{outline:'2px solid #825bea'}:undefined}><span className="business-card__label">{plan.tier==='BUSINESS'?<Database size={16}/>:plan.tier==='PRO'?<Bot size={16}/>:<FileText size={16}/>} {plan.name}</span><strong className="business-card__value">{plan.monthlyPriceUzs?`${compact(plan.monthlyPriceUzs, dateLocale)} ${t('billing.currency',"so'm")}`:t('billing.free','Bepul')}</strong><div className="business-list" style={{marginTop:14}}><span><Check size={14}/> {t('billing.perMonth',"Oyiga")} {compact(plan.limits.aiMessagesPerMonth, dateLocale)} {t('billing.aiMessageUnit','AI xabar')}</span><span><Check size={14}/> {compact(plan.limits.toolActionsPerMonth, dateLocale)} {t('billing.toolActionUnit','agent amali')}</span><span><Check size={14}/> {compact(plan.limits.files, dateLocale)} {t('billing.fileUnit','fayl')} · {compact(plan.limits.storageMb, dateLocale)} MB</span><span><Check size={14}/> {compact(plan.limits.memories, dateLocale)} {t('billing.memoryUnit','xotira')}</span></div><button className="business-button business-button--ghost" style={{width:'100%',marginTop:18}} disabled>{t('billing.paymentSoon','Payme / Click tez kunda')}</button></article>)}</section>
  </main>;
};
export default Billing;
