import React,{useEffect,useMemo,useRef,useState} from 'react'
import {NavLink,Outlet,useLocation,useNavigate} from 'react-router-dom'
import {
  LayoutDashboard,ShoppingBag,Boxes,Warehouse,ShoppingCart,Users,Truck,WalletCards,BarChart3,UserRoundCog,Settings,
  Search,CalendarDays,Bell,Sparkles,ChevronDown,ChevronRight,ChevronLeft,LogOut,Expand,SunMoon,Building2,CircleDollarSign,
  Globe2,Command,PackageSearch,UserRoundSearch,ReceiptText,Maximize2,X,Send,Menu,Check,AlertTriangle
} from 'lucide-react'
import {useApp} from '../state/AppContext'

const nav=[
  ['/',LayoutDashboard,'Boshqaruv paneli'],['/sales',ShoppingBag,'Savdo'],['/products',Boxes,'Mahsulotlar'],['/warehouse',Warehouse,'Ombor'],
  ['/purchases',ShoppingCart,'Xaridlar'],['/customers',Users,'Mijozlar'],['/suppliers',Truck,'Yetkazib beruvchilar'],['/finance',WalletCards,'Moliya'],
  ['/reports',BarChart3,'Hisobotlar'],['/employees',UserRoundCog,'Xodimlar'],['/settings',Settings,'Sozlamalar']
]
const routeModule={'/':'dashboard','/sales':'sales','/products':'products','/warehouse':'warehouse','/purchases':'purchases','/customers':'customers','/suppliers':'suppliers','/finance':'finance','/reports':'reports','/employees':'employees','/settings':'settings','/ai':'ai','/pos':'pos'}

const subnav={
  '/sales':{title:'Savdo',items:[['overview','Umumiy'],['pos','Yangi savdo / POS'],['history','Sotuvlar tarixi'],['returns','Qaytarishlar'],['credit','Nasiya'],['registers','Kassalar / Smenalar']]},
  '/products':{title:'Mahsulotlar',items:[['all','Barcha mahsulotlar'],['categories','Kategoriyalar'],['prices','Narxlar'],['import','Import'],['export','Export']]},
  '/warehouse':{title:'Ombor',items:[['stock','Qoldiqlar'],['movements','Harakatlar'],['transfer','Transfer'],['inventory','Inventarizatsiya'],['expiry','Srok / Partiyalar']]},
  '/purchases':{title:'Xaridlar',items:[['all','Xaridlar'],['receiving','Qabul qilish'],['returns','Qaytarishlar']]},
  '/customers':{title:'Mijozlar',items:[['all','Mijozlar'],['debts','Qarzdorlik'],['loyalty','Bonus / Loyalty'],['groups','Guruhlar']]},
  '/suppliers':{title:'Yetkazib beruvchilar',items:[['overview','Umumiy'],['all','Yetkazib beruvchilar'],['products','Mahsulotlar'],['debts','Qarzdorlik'],['history','Xarid tarixi'],['payments','To‘lovlar'],['documents','Hujjatlar'],['returns','Qaytarishlar']]},
  '/finance':{title:'Moliya',items:[['overview','Umumiy'],['transactions','Kirim-chiqim'],['accounts','Kassalar va hisoblar'],['debts','Qarzdorlik'],['pl','Foyda va zarar'],['cashflow','Cash Flow']]},
  '/reports':{title:'Hisobotlar',items:[['overview','Umumiy'],['sales','Savdo'],['products','Mahsulotlar'],['warehouse','Ombor'],['purchases','Xaridlar'],['customers','Mijozlar'],['finance','Moliya'],['debts','Qarzdorlik']]},
  '/employees':{title:'Xodimlar',items:[['all','Xodimlar'],['roles','Rollar va ruxsatlar'],['shifts','Smenalar'],['attendance','Davomat'],['payroll','Ish haqi / KPI'],['activity','Faoliyat']]},
  '/settings':{title:'Sozlamalar',items:[['company','Kompaniya'],['locations','Filiallar va omborlar'],['pos','Savdo / POS'],['finance','Moliya va to‘lovlar'],['products','Mahsulotlar va narxlar'],['purchases','Xaridlar va supplierlar'],['customers','Mijozlar'],['employees','Xodimlar va rollar'],['notifications','Bildirishnomalar'],['ai','ZENIX AI'],['appearance','Ko‘rinish'],['system','Integratsiyalar va tizim']]}
}
const defaults={'/sales':'overview','/products':'all','/warehouse':'stock','/purchases':'all','/customers':'all','/suppliers':'overview','/finance':'overview','/reports':'overview','/employees':'all','/settings':'company'}

export default function AppLayout(){
  const [collapsed,setCollapsed]=useState(false),[flyout,setFlyout]=useState(null),[aiOpen,setAiOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[search,setSearch]=useState(''),[notif,setNotif]=useState(false),[topMenu,setTopMenu]=useState(null)
  const {state,useCredit,saveSettings,currentEmployee,currentRole,can}=useApp();const navigate=useNavigate(),location=useLocation();const searchWrap=useRef(null)
  const currentView=new URLSearchParams(location.search).get('view')||defaults[location.pathname]

  useEffect(()=>{const fn=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(true);setTimeout(()=>searchWrap.current?.querySelector('input')?.focus(),0)}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[])
  useEffect(()=>{setFlyout(null);setTopMenu(null);setNotif(false)},[location.pathname,location.search])
  const results=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return null;return {products:can('products')?state.products.filter(x=>(x.name+' '+x.sku+' '+x.barcode).toLowerCase().includes(q)).slice(0,4):[],customers:can('customers')?state.customers.filter(x=>(x.name+' '+x.phone).toLowerCase().includes(q)).slice(0,4):[],sales:can('sales')?state.sales.filter(x=>(x.id+' '+x.customer).toLowerCase().includes(q)).slice(0,4):[],suppliers:can('suppliers')?state.suppliers.filter(x=>(x.name+' '+x.phone).toLowerCase().includes(q)).slice(0,3):[]}},[search,state,can])
  const openSub=(path,key)=>{if(path==='/sales'&&key==='pos'){navigate('/pos');setFlyout(null);return}navigate(`${path}?view=${key}`);setFlyout(null)}
  const toggleTheme=()=>saveSettings({theme:state.settings.theme==='dark'?'light':'dark'})
  const toggleFullscreen=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{}}
  const activeBranch=state.branches.find(x=>x.id===state.settings.defaultBranchId),activeWarehouse=state.warehouses.find(x=>x.id===state.settings.defaultWarehouseId)
  const visibleNav=nav.filter(([to])=>can(routeModule[to]||'dashboard'))
  const visibleNotifications=state.notifications.filter(n=>canSeeNotification(n,can))
  const setContext=(patch)=>{saveSettings(patch);setTopMenu(null)}
  const warehousesForBranch=state.warehouses.filter(w=>w.branchId===(state.settings.defaultBranchId||activeBranch?.id)&&w.status!=='Arxiv')
  const openTop=name=>{setNotif(false);setTopMenu(v=>v===name?null:name)}

  return <div className={`app-shell ${collapsed?'is-collapsed':''}`}>
    <div className="ambient ambient-a"/><div className="ambient ambient-b"/>
    <aside className="sidebar liquid-panel" onMouseLeave={()=>setFlyout(null)}>
      <div className="brand"><div className="brand-mark"><i/><i/><i/><i/></div>{!collapsed&&<div className="brand-copy"><b>ZENIX</b><span>Savdo</span></div>}</div>
      <nav className="nav">{visibleNav.map(([to,Icon,label])=><div className="nav-wrap" key={to} onMouseEnter={()=>subnav[to]&&setFlyout(to)}><NavLink to={to} end={to==='/'} className={({isActive})=>isActive?'nav-item active':'nav-item'}><Icon size={19}/>{!collapsed&&<span>{label}</span>}{!collapsed&&subnav[to]&&<ChevronRight className="nav-chevron" size={14}/>}</NavLink></div>)}</nav>
      <div className="sidebar-bottom">{can('ai')&&state.settings.ai.enabled&&<button className="ai-sidebar" onClick={()=>navigate('/ai')}><span className="ai-icon-wrap"><Sparkles size={18}/></span>{!collapsed&&<div><b>ZENIX AI</b><small>AI yordamchi</small></div>}</button>}<div className="bottom-utility"><button className="logout" onClick={()=>{setTopMenu(null);navigate('/settings?view=system')}} title="Sessiya va xavfsizlik"><LogOut size={18}/>{!collapsed&&<span>Sessiya</span>}</button><button className="collapse-btn" onClick={()=>setCollapsed(v=>!v)}>{collapsed?<ChevronRight size={16}/>:<ChevronLeft size={16}/>}</button></div></div>
      {flyout&&subnav[flyout]&&<div className="module-flyout liquid-panel" onMouseEnter={()=>setFlyout(flyout)} onMouseLeave={()=>setFlyout(null)}><div className="module-flyout-head"><span>BO‘LIM</span><h3>{subnav[flyout].title}</h3><small>Kerakli ishga tez o‘ting</small></div><div className="module-flyout-list">{subnav[flyout].items.map(([key,label])=><button key={key} className={location.pathname===flyout&&currentView===key?'active':''} onClick={()=>openSub(flyout,key)}><span>{label}</span><ChevronRight size={14}/></button>)}</div>{can('ai')&&state.settings.ai.enabled&&<button className="module-ai" onClick={()=>{setFlyout(null);setAiOpen(true)}}><Sparkles size={16}/><span><b>AI bilan amal</b><small>{subnav[flyout].title} kontekstida</small></span></button>}</div>}
    </aside>

    <div className="main-area">
      <header className="topbar liquid-panel">
        <div className="search-wrap" ref={searchWrap}><div className="search-box"><Search size={17}/><input value={search} onFocus={()=>setSearchOpen(true)} onChange={e=>{setSearch(e.target.value);setSearchOpen(true)}} placeholder="Mahsulot, mijoz, savdo, hujjat yoki raqam..."/><kbd>Ctrl K</kbd></div>{searchOpen&&<GlobalSearchDropdown results={results} query={search} close={()=>setSearchOpen(false)} navigate={navigate}/>}</div>
        <div className="top-menu-wrap"><button className="context-chip" onClick={()=>openTop('context')}><Building2 size={15}/><span>{activeBranch?.name||'Asosiy filial'} · {activeWarehouse?.name||'Asosiy ombor'}</span><ChevronDown size={13}/></button>{topMenu==='context'&&<ContextMenu state={state} branchId={state.settings.defaultBranchId} warehouseId={state.settings.defaultWarehouseId} warehouses={warehousesForBranch} onChange={setContext}/>}</div>
        <div className="top-actions"><div className="date-pill static-pill"><CalendarDays size={15}/> Bugun, 5 Sent 2026</div><div className="top-menu-wrap"><button className="top-pill" onClick={()=>openTop('currency')}><CircleDollarSign size={15}/>{state.settings.currency}</button>{topMenu==='currency'&&<ChoiceMenu title="Valyuta" value={state.settings.currency} options={['UZS','USD','EUR']} onPick={v=>setContext({currency:v})}/>}</div><div className="top-menu-wrap"><button className="top-pill" onClick={()=>openTop('language')}><Globe2 size={15}/>{state.settings.language}</button>{topMenu==='language'&&<ChoiceMenu title="Til" value={state.settings.language} options={[['UZ','O‘zbek'],['RU','Русский'],['EN','English']]} onPick={v=>setContext({language:v})}/>}</div><button className="icon-btn" onClick={toggleTheme} title="Light / Dark"><SunMoon size={17}/></button><button className="icon-btn" onClick={toggleFullscreen}><Expand size={17}/></button><div className="notif-wrap"><button className="icon-btn notification-btn" onClick={()=>{setTopMenu(null);setNotif(v=>!v)}}><Bell size={17}/>{visibleNotifications.some(n=>!n.read)&&<i/>}</button>{notif&&<NotificationMenu rows={visibleNotifications} close={()=>setNotif(false)}/>}</div>{can('ai')&&state.settings.ai.enabled&&<button className="ai-top" onClick={()=>setAiOpen(true)}><Sparkles size={16}/> ZENIX AI</button>}<div className="top-menu-wrap"><button className="profile" onClick={()=>openTop('profile')}><div className="avatar">{(currentEmployee?.name||'U').slice(0,1).toUpperCase()}</div><div><b>{currentEmployee?.name||'User'}</b><small>{currentRole?.name||currentEmployee?.role||'Rol'}</small></div><ChevronDown size={13}/></button>{topMenu==='profile'&&<ProfileMenu employee={currentEmployee} role={currentRole} can={can} navigate={navigate} close={()=>setTopMenu(null)}/>}</div></div>
      </header>
      <main className="content"><Outlet/></main>
    </div>
    {searchOpen&&<div className="search-dismiss" onClick={()=>setSearchOpen(false)}/>} {topMenu&&<div className="top-menu-dismiss" onClick={()=>setTopMenu(null)}/>} 
    {aiOpen&&can('ai')&&<QuickAI onClose={()=>setAiOpen(false)} credits={state.aiCredits} useCredit={useCredit} state={state} navigate={navigate} can={can}/>} 
  </div>
}

function ChoiceMenu({title,value,options,onPick}){return <div className="top-popover liquid-panel"><div className="top-popover-title">{title}</div><div className="choice-list">{options.map(o=>{const v=Array.isArray(o)?o[0]:o,l=Array.isArray(o)?o[1]:o;return <button key={v} className={value===v?'active':''} onClick={()=>onPick(v)}><span>{l}</span>{value===v&&<Check size={15}/>}</button>})}</div></div>}
function ContextMenu({state,branchId,warehouseId,warehouses,onChange}){return <div className="top-popover context-popover liquid-panel"><div className="top-popover-title">Ish konteksti</div><label>Filial</label><div className="choice-list compact-list">{state.branches.filter(b=>b.status!=='Arxiv').map(b=><button key={b.id} className={branchId===b.id?'active':''} onClick={()=>{const first=state.warehouses.find(w=>w.branchId===b.id&&w.status!=='Arxiv');onChange({defaultBranchId:b.id,defaultWarehouseId:first?.id||''})}}><span>{b.name}</span>{branchId===b.id&&<Check size={14}/>}</button>)}</div><label>Ombor</label><div className="choice-list compact-list">{warehouses.map(w=><button key={w.id} className={warehouseId===w.id?'active':''} onClick={()=>onChange({defaultWarehouseId:w.id})}><span>{w.name}</span>{warehouseId===w.id&&<Check size={14}/>}</button>)}</div></div>}
function ProfileMenu({employee,role,can,navigate,close}){return <div className="top-popover profile-popover liquid-panel"><div className="profile-popover-head"><div className="avatar large">{(employee?.name||'U').slice(0,1).toUpperCase()}</div><div><b>{employee?.name||'User'}</b><span>{role?.name||employee?.role||'Rol'}</span></div></div><div className="choice-list">{can('employees')&&<button onClick={()=>{navigate('/employees');close()}}><span>Xodim profilim</span><ChevronRight size={14}/></button>}{can('settings')&&<button onClick={()=>{navigate('/settings?view=appearance');close()}}><span>Ko‘rinish</span><ChevronRight size={14}/></button>}<button onClick={()=>{navigate('/settings?view=system');close()}}><span>Sessiya va xavfsizlik</span><ChevronRight size={14}/></button></div></div>}
function canSeeNotification(n,can){const t=String(n?.type||'').toLowerCase();if(['stock','expiry','inventory','transfer'].some(x=>t.includes(x)))return can('warehouse')||can('products');if(t.includes('shift')||t.includes('employee'))return can('employees')||can('sales');if(t.includes('debt')||t.includes('payment')||t.includes('cash'))return can('finance')||can('customers')||can('suppliers');if(t.includes('purchase')||t.includes('supplier'))return can('purchases')||can('suppliers');return true}
function NotificationMenu({rows,close}){return <div className="notification-menu liquid-panel"><div className="notification-title"><b>Bildirishnomalar</b><span>{rows.filter(x=>!x.read).length} yangi</span></div>{rows.slice(0,5).map(n=><div key={n.id} className="notification-row"><span className={`notification-dot ${n.severity}`}>{n.severity==='warning'?<AlertTriangle/>:<Check/>}</span><div><b>{n.title}</b><small>{n.text}</small></div></div>)}<button onClick={close}>Yopish</button></div>}
function GlobalSearchDropdown({results,query,close,navigate}){if(!query)return <div className="global-search-dropdown"><div className="search-empty-state"><Command/><div><b>Global qidiruv</b><span>Mahsulot, mijoz, chek, supplier yoki hujjatni yozing.</span></div></div></div>;const empty=results&&Object.values(results).every(a=>!a.length);return <div className="global-search-dropdown">{empty&&<div className="search-empty-state"><Search/><div><b>Natija topilmadi</b><span>“{query}” uchun boshqa so‘z bilan qidiring.</span></div></div>}{!!results?.products.length&&<SearchGroup icon={PackageSearch} title="Mahsulotlar" items={results.products.map(x=>[x.name,`${x.sku} · ${x.stock} ${x.unit}`])} onOpen={()=>{close();navigate('/products')}}/>}{!!results?.customers.length&&<SearchGroup icon={UserRoundSearch} title="Mijozlar" items={results.customers.map(x=>[x.name,x.phone])} onOpen={()=>{close();navigate('/customers')}}/>}{!!results?.suppliers.length&&<SearchGroup icon={Truck} title="Supplierlar" items={results.suppliers.map(x=>[x.name,x.phone])} onOpen={()=>{close();navigate('/suppliers?view=all')}}/>}{!!results?.sales.length&&<SearchGroup icon={ReceiptText} title="Savdolar" items={results.sales.map(x=>[x.id,`${x.customer} · ${Number(x.amount).toLocaleString('uz-UZ')} so‘m`])} onOpen={()=>{close();navigate('/sales?view=history')}}/>}</div>}
function SearchGroup({icon:Icon,title,items,onOpen}){return <div className="search-group"><div className="search-group-title"><Icon size={15}/>{title}</div>{items.map(([a,b],i)=><button key={i} onClick={onOpen}><b>{a}</b><span>{b}</span></button>)}</div>}
function QuickAI({onClose,credits,useCredit,state,navigate,can}){const [q,setQ]=useState(''),[msgs,setMsgs]=useState([{role:'ai',text:'Salom! Men ZENIX AI. Sizga ruxsat berilgan ma’lumotlar doirasida yordam beraman.'}]);const suggestions=[can('sales')&&'Bugungi savdo qancha?',can('customers')&&'Overdue qarzlarni top',can('warehouse')&&'Kam qolgan mahsulotlarni ko‘rsat'].filter(Boolean);const send=()=>{if(!q.trim()||credits<=0)return;const t=q.trim();setQ('');useCredit(1);setMsgs(m=>[...m,{role:'user',text:t},{role:'ai',text:answer(t,state,can)}])};return <div className="ai-overlay" onClick={onClose}><aside className="ai-panel liquid-panel" onClick={e=>e.stopPropagation()}><div className="ai-head"><div><Sparkles/><b>ZENIX AI</b><small>{credits} kredit</small></div><div><button onClick={()=>{onClose();navigate('/ai')}}><Maximize2 size={16}/></button><button onClick={onClose}><X size={18}/></button></div></div><div className="ai-suggestions">{suggestions.map(x=><button key={x} onClick={()=>setQ(x)}>{x}</button>)}</div><div className="ai-messages">{msgs.map((m,i)=><div key={i} className={`msg ${m.role}`}>{m.text}</div>)}</div><div className="ai-input"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={credits?'Savol yozing...':'Demo kredit tugadi'}/><button onClick={send}><Send size={17}/></button></div></aside></div>}
function answer(t,s,can){const q=t.toLowerCase();if(q.includes('savdo')&&!can('sales'))return 'Savdo ma’lumotlarini ko‘rish uchun ruxsatingiz yo‘q.';if(q.includes('qarz')&&!can('customers')&&!can('finance'))return 'Qarzdorlik ma’lumotlarini ko‘rish uchun ruxsatingiz yo‘q.';if(q.includes('kam')&&!can('warehouse')&&!can('products'))return 'Ombor ma’lumotlarini ko‘rish uchun ruxsatingiz yo‘q.';if(q.includes('savdo'))return `Jami savdo: ${s.sales.reduce((a,x)=>a+x.amount,0).toLocaleString('uz-UZ')} so‘m. ${s.sales.length} ta chek.`;if(q.includes('qarz'))return `Mijozlar qarzi ${s.customers.reduce((a,x)=>a+x.debt,0).toLocaleString('uz-UZ')} so‘m, supplier majburiyatlari ${s.supplierDebts.reduce((a,x)=>a+Math.max(0,x.amount-x.paid),0).toLocaleString('uz-UZ')} so‘m.`;if(q.includes('kam'))return `${s.products.filter(p=>p.stock<=p.minStock).map(p=>p.name).join(', ')||'Kam qolgan mahsulot yo‘q'}.`;return 'Tahlil tayyor. ZENIX AI ruxsatlaringiz doirasidagi ma’lumotlar asosida javob beradi.'}
